/* Generated by Nim Compiler v1.3.5 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <sys/types.h>
                          #include <pthread.h>
#include <string.h>
#include <setjmp.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_AsyncHttpServercolonObjectType___9blhbIPPCWUB8g9b1PZ6GMnw tyObject_AsyncHttpServercolonObjectType___9blhbIPPCWUB8g9b1PZ6GMnw;
typedef struct tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w;
typedef struct tyObject_Request__1Wfxxtqzahm0R6lueM9aQmQ tyObject_Request__1Wfxxtqzahm0R6lueM9aQmQ;
typedef struct tyObject_Env_example_serverdotnim___m15TreKjsI9ax7nUqERmdaQ tyObject_Env_example_serverdotnim___m15TreKjsI9ax7nUqERmdaQ;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_AsyncSocketDesc__D7quBEmo0QGfBsms9bXpWfg tyObject_AsyncSocketDesc__D7quBEmo0QGfBsms9bXpWfg;
typedef struct tyObject_HttpHeaderscolonObjectType___GM611pWlOrQ7hvMPcuAACA tyObject_HttpHeaderscolonObjectType___GM611pWlOrQ7hvMPcuAACA;
typedef struct tyTuple__kN8up2W6YKc5YA9avn5mV5w tyTuple__kN8up2W6YKc5YA9avn5mV5w;
typedef struct tyObject_Uri__j49bukNPrq747O1GRd4Ng9bQ tyObject_Uri__j49bukNPrq747O1GRd4Ng9bQ;
typedef struct tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw;
typedef struct tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg;
typedef struct tyObject_Env_asyncmacrodotnim___nDq9c3JWrEMiahPRz1h5tLw tyObject_Env_asyncmacrodotnim___nDq9c3JWrEMiahPRz1h5tLw;
typedef struct tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ;
typedef struct Exception Exception;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct TSafePoint TSafePoint;
typedef struct tyObject_AssertionDefect__PtYxPmY5X0dorfvxAFbJpQ tyObject_AssertionDefect__PtYxPmY5X0dorfvxAFbJpQ;
typedef struct tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;

/* section: NIM_merge_TYPES */
struct TGenericSeq {NI len;
NI reserved;
};
struct NimStringDesc {  TGenericSeq Sup;NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* tyArray__nHXaesL0DJZHyVS07ARPRA[1];
typedef struct {
N_NIMCALL_PTR(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w*, ClP_0) (tyObject_Request__1Wfxxtqzahm0R6lueM9aQmQ* request, void* ClE_0);
void* ClE_0;
} tyProc__czO9bLH6rWgTeb5AIcTKy5g;
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {TNimType* m_type;};
typedef NU8 tyEnum_HttpMethod__wfZHspwVKQPl9aWhkIcMrAA;
struct tyTuple__kN8up2W6YKc5YA9avn5mV5w {
NimStringDesc* Field0;
NI Field1;
NI Field2;
};
struct tyObject_Uri__j49bukNPrq747O1GRd4Ng9bQ {NimStringDesc* scheme;
NimStringDesc* username;
NimStringDesc* password;
NimStringDesc* hostname;
NimStringDesc* port;
NimStringDesc* path;
NimStringDesc* query;
NimStringDesc* anchor;
NIM_BOOL opaque;
};
struct tyObject_Request__1Wfxxtqzahm0R6lueM9aQmQ {tyObject_AsyncSocketDesc__D7quBEmo0QGfBsms9bXpWfg* client;
tyEnum_HttpMethod__wfZHspwVKQPl9aWhkIcMrAA reqMethod;
tyObject_HttpHeaderscolonObjectType___GM611pWlOrQ7hvMPcuAACA* headers;
tyTuple__kN8up2W6YKc5YA9avn5mV5w protocol;
tyObject_Uri__j49bukNPrq747O1GRd4Ng9bQ url;
NimStringDesc* hostname;
NimStringDesc* body;
};
typedef struct {
N_NIMCALL_PTR(tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA*, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__uz49bJm19cqLWB77G7nLz3FA;
struct tyObject_Env_example_serverdotnim___m15TreKjsI9ax7nUqERmdaQ {  RootObj Sup;NI colonstate_;
tyObject_Request__1Wfxxtqzahm0R6lueM9aQmQ req1;
tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* retFuture2;
tyProc__uz49bJm19cqLWB77G7nLz3FA nameIterVarX60gensym310560183_;
tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* retFutUnownX60gensym310560174_;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SPr7N6UKfuF549bNPiUvSRw[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {NI minLargeObj;
NI maxLargeObj;
tyArray__SPr7N6UKfuF549bNPiUvSRw freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw {tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg* head;
tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg* tail;
pthread_mutex_t lock;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw toDispose;
NI gcThreadId;
};
struct tyObject_Env_asyncmacrodotnim___nDq9c3JWrEMiahPRz1h5tLw {  RootObj Sup;NI colonstate_;
tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA* internalTmpFutureX60gensym31056023X60gensym310600321_;
tyObject_Env_example_serverdotnim___m15TreKjsI9ax7nUqERmdaQ* colonup_;
tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA* result3;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__HzVCwACFYM9cx9aV62PdjtuA;
struct tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ {tyProc__HzVCwACFYM9cx9aV62PdjtuA function;
tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ* next;
};
struct tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA {  RootObj Sup;tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ callbacks;
NIM_BOOL finished;
Exception* error;
NimStringDesc* errorStackTrace;
tySequence__uB9b75OUPRENsBAu4AnoePA* stackTrace;
NI id;
NimStringDesc* fromProc;
};
struct tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w {  tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA Sup;};
struct Exception {  RootObj Sup;Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence__uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct TSafePoint {TSafePoint* prev;
NI status;
jmp_buf context;
};
typedef N_CLOSURE_PTR(tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA*, TM__F2tqCOO6WDiND6xhXZOuUw_9) (void);
typedef N_CLOSURE_PTR(tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA*, TM__F2tqCOO6WDiND6xhXZOuUw_10) (void);
struct tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA {  Exception Sup;};
struct tyObject_AssertionDefect__PtYxPmY5X0dorfvxAFbJpQ {  tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA Sup;};
typedef N_CLOSURE_PTR(void, TM__F2tqCOO6WDiND6xhXZOuUw_12) (void);
typedef N_CLOSURE_PTR(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w*, TM__F2tqCOO6WDiND6xhXZOuUw_13) (tyObject_Request__1Wfxxtqzahm0R6lueM9aQmQ* request, void* ClE_0);
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {NCSTRING procname;
NI line;
NCSTRING filename;
};

/* section: NIM_merge_SEQ_TYPES */
struct tySequence__uB9b75OUPRENsBAu4AnoePA {  TGenericSeq Sup;  tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
/* section: NIM_merge_PROC_HEADERS */
N_LIB_PRIVATE N_NIMCALL(void, run_http_server)(void);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(tyObject_AsyncHttpServercolonObjectType___9blhbIPPCWUB8g9b1PZ6GMnw*, newAsyncHttpServer__3nt12aazkrwWwKRGH9bCj9bw)(NIM_BOOL reuseAddr, NIM_BOOL reusePort, NI maxBody);
N_LIB_PRIVATE N_NIMCALL(void, waitFor__zz9aVsJN0aTuFUXvzKrFo9cA)(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* fut);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w*, serve__PCNVS7VCLMlzsJOLb7Qi9bg)(tyObject_AsyncHttpServercolonObjectType___9blhbIPPCWUB8g9b1PZ6GMnw* server, NU16 port, tyProc__czO9bLH6rWgTeb5AIcTKy5g callback, NimStringDesc* address);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w*, cb__R1wzpMYDao07llKGNJV9aaQ)(tyObject_Request__1Wfxxtqzahm0R6lueM9aQmQ* req);
N_LIB_PRIVATE N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef__baZlsAq9c5BaiB74trUvOHw)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w*, newFuture__O5FiTIx7b9aJMbTMTl7J2SQ)(NimStringDesc* fromProc);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef__AT1eRuflKWyTTBdLjEDZbgsystem)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, pluspercent___dgYAo7RfdUVVpvkfKDym8w_2system)(NI x, NI y);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem)(void* usr);
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y);
static N_INLINE(void, decRef__AT1eRuflKWyTTBdLjEDZbg_2system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NIM_BOOL, ltpercent___hPljn3JCDQ00ua1R07X9bxQsystem)(NI x, NI y);
static N_INLINE(void, rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_3system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__Y66tOYFjgwJ0k4aLz4bc0Q)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_NIMCALL(void, Marker_tyRef__P9cJvr1z9ajzzZb5SJxD56xA)(void* p, NI op);
N_LIB_PRIVATE N_CLOSURE(tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA*, cbIter__mAuTRAkOPFmW9aSKpTLnZWg)(void* ClE_0);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w*, respond__tA4fbg9cx0zS1ZvSTtksr9bQ)(tyObject_Request__1Wfxxtqzahm0R6lueM9aQmQ* req, NI code, NimStringDesc* content, tyObject_HttpHeaderscolonObjectType___GM611pWlOrQ7hvMPcuAACA* headers);
N_LIB_PRIVATE N_NIMCALL(void, read__kYv5uOSTaUb7hZbxPjTMHA_3)(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* future);
N_LIB_PRIVATE N_NIMCALL(void, complete__kYv5uOSTaUb7hZbxPjTMHA)(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* future);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size);
N_LIB_PRIVATE N_CLOSURE(void, cbNimAsyncContinue__9bVdb9bX5YIpmecEjobmcpQQ)(void* ClE_0);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_INLINE(NIM_BOOL, finished__SDzjUskCcAHghx1ZNCiJfwsystem)(tyProc__uz49bJm19cqLWB77G7nLz3FA x);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, finished__Cn8FMZpHNs40shvQ9cZz69aA_2)(tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA* future);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, finished__zLPHIdTAe2mgu9c9c1y5dGIQ)(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* future);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuFormatSingleElem)(NimStringDesc* formatstr, NimStringDesc* a);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
N_LIB_PRIVATE N_NIMCALL(void, addCallback__LPYaMz3j7An9cL9cbuTYEaOQ_2)(tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA* future, tyProc__HzVCwACFYM9cx9aV62PdjtuA cb);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(TFrame*, getFrame)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_LIB_PRIVATE N_NIMCALL(void, reraiseException)(void);
N_LIB_PRIVATE N_NIMCALL(void, fail__KP9b34veEV0ehqMJglv63VQ)(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* future, Exception* error);
static N_INLINE(Exception*, getCurrentException)(void);
static N_INLINE(void, popCurrentException)(void);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_LIB_PRIVATE N_NOINLINE(void, nimGC_setStackBottom)(void* theStackBottom);
N_LIB_PRIVATE N_NIMCALL(void, systemDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, systemInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_optionsDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_timesDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_timesInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_osDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_osInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_tablesDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_heapqueueDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_dequesDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_asyncfuturesDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_asyncfuturesInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_monotimesDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_nativesocketsDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_nativesocketsInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_netDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_selectorsDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_asyncdispatchDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_asyncdispatchInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_asyncnetDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_uriDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_httpcoreDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_asynchttpserverDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, example_serverDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);

/* section: NIM_merge_DATA */
STRING_LITERAL(TM__F2tqCOO6WDiND6xhXZOuUw_3, "starting http server", 20);
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__F2tqCOO6WDiND6xhXZOuUw_2 = {((NimStringDesc*) &TM__F2tqCOO6WDiND6xhXZOuUw_3)}
;
extern TNimType NTI__ytyiCJqK439aF9cIibuRVpAg_;
N_LIB_PRIVATE TNimType NTI__m15TreKjsI9ax7nUqERmdaQ_;
extern TNimType NTI__xHTZrq9aYs6boc9bCba0JbpQ_;
extern TNimType NTI__1Wfxxtqzahm0R6lueM9aQmQ_;
extern TNimType NTI__TjokxNjmnZmr9bygVDVC9bvg_;
extern TNimType NTI__uz49bJm19cqLWB77G7nLz3FA_;
N_LIB_PRIVATE TNimType NTI__baZlsAq9c5BaiB74trUvOHw_;
STRING_LITERAL(TM__F2tqCOO6WDiND6xhXZOuUw_5, "cb", 2);
N_LIB_PRIVATE TNimType NTI__nDq9c3JWrEMiahPRz1h5tLw_;
extern TNimType NTI__G3WIkXk4MjMLVyyUid6IEw_;
N_LIB_PRIVATE TNimType NTI__P9cJvr1z9ajzzZb5SJxD56xA_;
STRING_LITERAL(TM__F2tqCOO6WDiND6xhXZOuUw_7, "Hello World", 11);
STRING_LITERAL(TM__F2tqCOO6WDiND6xhXZOuUw_11, "Async procedure ($1) yielded `nil`, are you await\'ing a `nil` F"
"uture\?", 69);
extern TNimType NTI__S8DV6hfcgC9c0IiUsAoR29cQ_;
extern TNimType NTI__PtYxPmY5X0dorfvxAFbJpQ_;
STRING_LITERAL(TM__F2tqCOO6WDiND6xhXZOuUw_15, "running server", 14);
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__F2tqCOO6WDiND6xhXZOuUw_14 = {((NimStringDesc*) &TM__F2tqCOO6WDiND6xhXZOuUw_15)}
;

/* section: NIM_merge_VARS */
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch__IcYaEuuWivYAS86vFMTS3Q;
extern NIM_THREADVAR TSafePoint* excHandler__rqLlY5bs9atDw2OXYqJEn5g;
extern NIM_THREADVAR TSafePoint* excHandler__rqLlY5bs9atDw2OXYqJEn5g;
extern NIM_THREADVAR TSafePoint* excHandler__rqLlY5bs9atDw2OXYqJEn5g;
extern NIM_THREADVAR TSafePoint* excHandler__rqLlY5bs9atDw2OXYqJEn5g;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR Exception* currException__9bVPeDJlYTi9bQApZpfH8wjg;
extern NIM_THREADVAR Exception* currException__9bVPeDJlYTi9bQApZpfH8wjg;
extern NIM_THREADVAR Exception* currException__9bVPeDJlYTi9bQApZpfH8wjg;

/* section: NIM_merge_PROCS */
static N_NIMCALL(void, Marker_tyRef__baZlsAq9c5BaiB74trUvOHw)(void* p, NI op) {
	tyObject_Env_example_serverdotnim___m15TreKjsI9ax7nUqERmdaQ* a;
	a = (tyObject_Env_example_serverdotnim___m15TreKjsI9ax7nUqERmdaQ*)p;
	nimGCvisit((void*)(*a).req1.client, op);	nimGCvisit((void*)(*a).req1.headers, op);	nimGCvisit((void*)(*a).req1.protocol.Field0, op);	nimGCvisit((void*)(*a).req1.url.scheme, op);	nimGCvisit((void*)(*a).req1.url.username, op);	nimGCvisit((void*)(*a).req1.url.password, op);	nimGCvisit((void*)(*a).req1.url.hostname, op);	nimGCvisit((void*)(*a).req1.url.port, op);	nimGCvisit((void*)(*a).req1.url.path, op);	nimGCvisit((void*)(*a).req1.url.query, op);	nimGCvisit((void*)(*a).req1.url.anchor, op);	nimGCvisit((void*)(*a).req1.hostname, op);	nimGCvisit((void*)(*a).req1.body, op);	nimGCvisit((void*)(*a).retFuture2, op);	nimGCvisit((void*)(*a).nameIterVarX60gensym310560183_.ClE_0, op);	nimGCvisit((void*)(*a).retFutUnownX60gensym310560174_, op);}

#line 549 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 550 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 550 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA3_;

#line 551 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 554 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 554 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 556 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 557 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 558 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 558 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 558 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 558 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}

#line 85 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 86 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}

#line 425 "/home/elcritch/.asdf/installs/nim/devel/lib/system/arithmetics.nim"
static N_INLINE(NI, pluspercent___dgYAo7RfdUVVpvkfKDym8w_2system)(NI x, NI y) {	NI result;	nimfr_("+%", "/home/elcritch/.asdf/installs/nim/devel/lib/system/arithmetics."
"nim");	result = (NI)0;
#line 426 "/home/elcritch/.asdf/installs/nim/devel/lib/system/arithmetics.nim"
	nimln_(426, "/home/elcritch/.asdf/installs/nim/devel/lib/system/arithmetics."
"nim");
#line 430 "/home/elcritch/.asdf/installs/nim/devel/lib/system/arithmetics.nim"
	nimln_(430, "/home/elcritch/.asdf/installs/nim/devel/lib/system/arithmetics."
"nim");	result = ((NI) ((NU)((NU32)(((NU) (x))) + (NU32)(((NU) (y))))));	popFrame();	return result;}

#line 182 "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim"
static N_INLINE(void, incRef__AT1eRuflKWyTTBdLjEDZbgsystem)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {	nimfr_("incRef", "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim");
#line 184 "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim"
	nimln_(184, "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim");
#line 184 "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim"
	(*c).refcount = pluspercent___dgYAo7RfdUVVpvkfKDym8w_2system((*c).refcount, ((NI) 8));	popFrame();}

#line 436 "/home/elcritch/.asdf/installs/nim/devel/lib/system/arithmetics.nim"
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y) {	NI result;	nimfr_("-%", "/home/elcritch/.asdf/installs/nim/devel/lib/system/arithmetics."
"nim");	result = (NI)0;
#line 437 "/home/elcritch/.asdf/installs/nim/devel/lib/system/arithmetics.nim"
	nimln_(437, "/home/elcritch/.asdf/installs/nim/devel/lib/system/arithmetics."
"nim");
#line 441 "/home/elcritch/.asdf/installs/nim/devel/lib/system/arithmetics.nim"
	nimln_(441, "/home/elcritch/.asdf/installs/nim/devel/lib/system/arithmetics."
"nim");	result = ((NI) ((NU)((NU32)(((NU) (x))) - (NU32)(((NU) (y))))));	popFrame();	return result;}

#line 128 "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim"
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem)(void* usr) {	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;	NI T1_;	nimfr_("usrToCell", "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim");	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
#line 130 "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim"
	nimln_(130, "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim");
#line 130 "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim"

#line 130 "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim"
	T1_ = (NI)0;	T1_ = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) (usr)), ((NI) 8));	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) (T1_));	popFrame();	return result;}

#line 187 "/home/elcritch/.asdf/installs/nim/devel/lib/system/comparisons.nim"
static N_INLINE(NIM_BOOL, ltpercent___hPljn3JCDQ00ua1R07X9bxQsystem)(NI x, NI y) {	NIM_BOOL result;	nimfr_("<%", "/home/elcritch/.asdf/installs/nim/devel/lib/system/comparisons."
"nim");	result = (NIM_BOOL)0;
#line 188 "/home/elcritch/.asdf/installs/nim/devel/lib/system/comparisons.nim"
	nimln_(188, "/home/elcritch/.asdf/installs/nim/devel/lib/system/comparisons."
"nim");
#line 190 "/home/elcritch/.asdf/installs/nim/devel/lib/system/comparisons.nim"
	nimln_(190, "/home/elcritch/.asdf/installs/nim/devel/lib/system/comparisons."
"nim");	result = ((NU32)(((NU) (x))) < (NU32)(((NU) (y))));	popFrame();	return result;}

#line 194 "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim"
static N_INLINE(void, rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_3system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {	nimfr_("rtlAddZCT", "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim");
#line 196 "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim"
	nimln_(196, "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim");
#line 196 "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim"
	addZCT__Y66tOYFjgwJ0k4aLz4bc0Q((&gch__IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();}

#line 198 "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim"
static N_INLINE(void, decRef__AT1eRuflKWyTTBdLjEDZbg_2system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {	nimfr_("decRef", "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim");
#line 201 "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim"
	nimln_(201, "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim");
#line 201 "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim"
	(*c).refcount = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem((*c).refcount, ((NI) 8));
#line 202 "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim"
	nimln_(202, "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim");	{		NIM_BOOL T3_;
#line 202 "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim"

#line 202 "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim"
		T3_ = (NIM_BOOL)0;		T3_ = ltpercent___hPljn3JCDQ00ua1R07X9bxQsystem((*c).refcount, ((NI) 8));		if (!T3_) goto LA4_;

#line 203 "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim"
		nimln_(203, "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim");
#line 203 "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim"
		rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_3system(c);
	}
	LA4_: ;
	popFrame();}

#line 235 "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim"
static N_INLINE(void, asgnRef)(void** dest, void* src) {	nimfr_("asgnRef", "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim");
#line 239 "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim"
	nimln_(239, "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim");	{		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T5_;
#line 239 "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim"

#line 239 "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim"
		if (!!((src == NIM_NIL))) goto LA3_;

#line 239 "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim"

#line 239 "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim"

#line 239 "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim"
		T5_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;		T5_ = usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem(src);
#line 239 "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim"
		incRef__AT1eRuflKWyTTBdLjEDZbgsystem(T5_);
	}
	LA3_: ;

#line 240 "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim"
	nimln_(240, "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim");	{		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T10_;
#line 240 "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim"

#line 240 "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim"
		if (!!(((*dest) == NIM_NIL))) goto LA8_;

#line 240 "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim"

#line 240 "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim"

#line 240 "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim"
		T10_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;		T10_ = usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem((*dest));
#line 240 "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim"
		decRef__AT1eRuflKWyTTBdLjEDZbg_2system(T10_);
	}
	LA8_: ;

#line 241 "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim"
	nimln_(241, "/home/elcritch/.asdf/installs/nim/devel/lib/system/gc.nim");	(*dest) = src;	popFrame();}
static N_NIMCALL(void, Marker_tyRef__P9cJvr1z9ajzzZb5SJxD56xA)(void* p, NI op) {
	tyObject_Env_asyncmacrodotnim___nDq9c3JWrEMiahPRz1h5tLw* a;
	a = (tyObject_Env_asyncmacrodotnim___nDq9c3JWrEMiahPRz1h5tLw*)p;
	nimGCvisit((void*)(*a).internalTmpFutureX60gensym31056023X60gensym310600321_, op);	nimGCvisit((void*)(*a).colonup_, op);	nimGCvisit((void*)(*a).result3, op);}

#line 205 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
N_LIB_PRIVATE N_CLOSURE(tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA*, cbIter__mAuTRAkOPFmW9aSKpTLnZWg)(void* ClE_0) {	tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA* result;	tyObject_Env_asyncmacrodotnim___nDq9c3JWrEMiahPRz1h5tLw* colonenvP_;	nimfr_("cbIter", "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim");{	result = (tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA*)0;	colonenvP_ = (tyObject_Env_asyncmacrodotnim___nDq9c3JWrEMiahPRz1h5tLw*) ClE_0;
#line 5 "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/nim/example_server.nim"
	nimln_(5, "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/ni"
"m/example_server.nim");	while (1) {		if (!1) goto LA1;
		{			tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* T3_;			switch ((*colonenvP_).colonstate_) {
			case -1:
			 goto BeforeRet_;
			case 0: goto STATE0;
			case 1: goto STATE1;
			case 2: goto STATE2;
			case 3: goto STATE3;
			}
			STATE0: ;
#line 271 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
			nimln_(271, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim");
#line 5 "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/nim/example_server.nim"
			nimln_(5, "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/ni"
"m/example_server.nim");
#line 5 "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/nim/example_server.nim"
			T3_ = (tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w*)0;			T3_ = respond__tA4fbg9cx0zS1ZvSTtksr9bQ((&(*(*colonenvP_).colonup_).req1), ((NI) 200), ((NimStringDesc*) &TM__F2tqCOO6WDiND6xhXZOuUw_7), NIM_NIL);			asgnRef((void**) (&(*colonenvP_).internalTmpFutureX60gensym31056023X60gensym310600321_), &T3_->Sup);
#line 0 "\?\?\?"
			(*colonenvP_).colonstate_ = ((NI) 1);
#line 272 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
			nimln_(272, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim");
#line 272 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
			result = (*colonenvP_).internalTmpFutureX60gensym31056023X60gensym310600321_;			goto BeforeRet_;
			STATE1: ;
#line 273 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
			nimln_(273, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim");
#line 273 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
			read__kYv5uOSTaUb7hZbxPjTMHA_3(((tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w*) ((*colonenvP_).internalTmpFutureX60gensym31056023X60gensym310600321_)));

#line 0 "\?\?\?"
			(*colonenvP_).colonstate_ = ((NI) 2);
#line 5 "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/nim/example_server.nim"
			nimln_(5, "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/ni"
"m/example_server.nim");			goto LA2;
			STATE2: ;
#line 5 "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/nim/example_server.nim"

#line 5 "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/nim/example_server.nim"
			complete__kYv5uOSTaUb7hZbxPjTMHA((*(*colonenvP_).colonup_).retFuture2);

#line 0 "\?\?\?"
			(*colonenvP_).colonstate_ = ((NI) 3);
#line 0 "\?\?\?"
			goto LA2;
			STATE3: ;
#line 0 "\?\?\?"
			(*colonenvP_).colonstate_ = ((NI) -1);
#line 0 "\?\?\?"
			goto LA2;
		} LA2: ;
	} LA1: ;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 22 "/home/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size) {	void* T1_;
#line 24 "/home/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"

#line 24 "/home/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memset(a, v, ((size_t) (size)));}

#line 33 "/home/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
#line 34 "/home/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"

#line 34 "/home/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
	nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory(p, ((int) 0), size);
}

#line 111 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
#line 112 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	(*s).prev = excHandler__rqLlY5bs9atDw2OXYqJEn5g;
#line 113 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	excHandler__rqLlY5bs9atDw2OXYqJEn5g = s;}

#line 2351 "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim"
static N_INLINE(NIM_BOOL, finished__SDzjUskCcAHghx1ZNCiJfwsystem)(tyProc__uz49bJm19cqLWB77G7nLz3FA x) {	NIM_BOOL result;	nimfr_("finished", "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim");	result = (NIM_BOOL)0;
#line 2353 "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim"
	nimln_(2353, "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim");	    result = ((NI*) x.ClE_0)[1] < 0;
    
	popFrame();	return result;}

#line 115 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, popSafePoint)(void) {
#line 116 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	excHandler__rqLlY5bs9atDw2OXYqJEn5g = (*excHandler__rqLlY5bs9atDw2OXYqJEn5g).prev;}

#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(TFrame*, getFrame)(void) {	TFrame* result;	result = (TFrame*)0;
#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	result = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;	return result;}

#line 100 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, setFrame)(TFrame* s) {
#line 101 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;}

#line 2310 "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim"
static N_INLINE(Exception*, getCurrentException)(void) {	Exception* result;	nimfr_("getCurrentException", "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim");	result = (Exception*)0;
#line 2312 "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim"
	nimln_(2312, "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim");	result = currException__9bVPeDJlYTi9bQApZpfH8wjg;	popFrame();	return result;}

#line 123 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, popCurrentException)(void) {
#line 124 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	asgnRef((void**) (&currException__9bVPeDJlYTi9bQApZpfH8wjg), (*currException__9bVPeDJlYTi9bQApZpfH8wjg).up);}

#line 245 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
N_LIB_PRIVATE N_CLOSURE(void, cbNimAsyncContinue__9bVdb9bX5YIpmecEjobmcpQQ)(void* ClE_0) {	tyObject_Env_example_serverdotnim___m15TreKjsI9ax7nUqERmdaQ* colonenvP_;	TSafePoint TM__F2tqCOO6WDiND6xhXZOuUw_8;	TFrame* _nimCurFrame;	nimfr_("cbNimAsyncContinue", "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim");	_nimCurFrame = getFrame();	colonenvP_ = (tyObject_Env_example_serverdotnim___m15TreKjsI9ax7nUqERmdaQ*) ClE_0;
#line 21 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
	nimln_(21, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim");	pushSafePoint(&TM__F2tqCOO6WDiND6xhXZOuUw_8);	TM__F2tqCOO6WDiND6xhXZOuUw_8.status = setjmp(TM__F2tqCOO6WDiND6xhXZOuUw_8.context);	if (TM__F2tqCOO6WDiND6xhXZOuUw_8.status == 0) {
#line 22 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
		nimln_(22, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim");		{			NIM_BOOL T4_;			tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA* volatile nextX60gensym31056019_;
#line 22 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"

#line 22 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"

#line 22 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
			T4_ = (NIM_BOOL)0;			T4_ = finished__SDzjUskCcAHghx1ZNCiJfwsystem((*colonenvP_).nameIterVarX60gensym310560183_);			if (!!(T4_)) goto LA5_;

#line 23 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
			nimln_(23, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim");			nextX60gensym31056019_ = (*colonenvP_).nameIterVarX60gensym310560183_.ClP_0((*colonenvP_).nameIterVarX60gensym310560183_.ClE_0);			{
#line 25 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
				nimln_(25, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim");				while (1) {					NIM_BOOL T9_;
#line 25 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
					T9_ = (NIM_BOOL)0;
#line 25 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"

#line 25 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
					T9_ = !((nextX60gensym31056019_ == 0));					if (!(T9_)) goto LA10_;

#line 25 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"

#line 25 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
					T9_ = finished__Cn8FMZpHNs40shvQ9cZz69aA_2(nextX60gensym31056019_);					LA10_: ;
					if (!T9_) goto LA8;

#line 26 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
					nimln_(26, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim");					nextX60gensym31056019_ = (*colonenvP_).nameIterVarX60gensym310560183_.ClP_0((*colonenvP_).nameIterVarX60gensym310560183_.ClE_0);
#line 27 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
					nimln_(27, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim");					{						NIM_BOOL T13_;
#line 27 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"

#line 27 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
						T13_ = (NIM_BOOL)0;						T13_ = finished__SDzjUskCcAHghx1ZNCiJfwsystem((*colonenvP_).nameIterVarX60gensym310560183_);						if (!T13_) goto LA14_;

#line 28 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
						nimln_(28, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim");						goto LA7;
					}
					LA14_: ;
				} LA8: ;
			} LA7: ;

#line 30 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
			nimln_(30, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim");			{
#line 30 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
				if (!(nextX60gensym31056019_ == NIM_NIL)) goto LA18_;

#line 31 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
				nimln_(31, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim");				{					NIM_BOOL T22_;					NimStringDesc* msgX60gensym31056020_;					tyObject_AssertionDefect__PtYxPmY5X0dorfvxAFbJpQ* T25_;
#line 31 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"

#line 31 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"

#line 31 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
					T22_ = (NIM_BOOL)0;					T22_ = finished__zLPHIdTAe2mgu9c9c1y5dGIQ((*colonenvP_).retFutUnownX60gensym310560174_);					if (!!(T22_)) goto LA23_;

#line 32 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
					nimln_(32, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim");					msgX60gensym31056020_ = copyString(((NimStringDesc*) &TM__F2tqCOO6WDiND6xhXZOuUw_11));					T25_ = (tyObject_AssertionDefect__PtYxPmY5X0dorfvxAFbJpQ*)0;					T25_ = (tyObject_AssertionDefect__PtYxPmY5X0dorfvxAFbJpQ*) newObj((&NTI__S8DV6hfcgC9c0IiUsAoR29cQ_), sizeof(tyObject_AssertionDefect__PtYxPmY5X0dorfvxAFbJpQ));					(*T25_).Sup.Sup.Sup.m_type = (&NTI__PtYxPmY5X0dorfvxAFbJpQ_);					(*T25_).Sup.Sup.name = "AssertionDefect";
#line 34 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
					nimln_(34, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim");
#line 34 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
					asgnRef((void**) (&(*T25_).Sup.Sup.message), nsuFormatSingleElem(msgX60gensym31056020_, ((NimStringDesc*) &TM__F2tqCOO6WDiND6xhXZOuUw_5)));					asgnRef((void**) (&(*T25_).Sup.Sup.parent), NIM_NIL);
#line 34 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
					raiseExceptionEx((Exception*)T25_, "AssertionDefect", "cbNimAsyncContinue", "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim", 34);				}
				LA23_: ;
			}
			goto LA16_;
			LA18_: ;
			{				tyProc__HzVCwACFYM9cx9aV62PdjtuA T27_;
#line 38 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
				nimln_(38, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim");				nimZeroMem((void*)(&T27_), sizeof(tyProc__HzVCwACFYM9cx9aV62PdjtuA));				T27_.ClP_0 = cbNimAsyncContinue__9bVdb9bX5YIpmecEjobmcpQQ; T27_.ClE_0 = colonenvP_;
#line 38 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
				addCallback__LPYaMz3j7An9cL9cbuTYEaOQ_2(nextX60gensym31056019_, T27_);
			}
			LA16_: ;
		}
		LA5_: ;
		popSafePoint();	}
	else {		popSafePoint();		setFrame(_nimCurFrame);		{			TM__F2tqCOO6WDiND6xhXZOuUw_8.status = 0;
#line 42 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
			nimln_(42, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim");			{				NIM_BOOL T32_;
#line 42 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"

#line 42 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
				T32_ = (NIM_BOOL)0;				T32_ = finished__zLPHIdTAe2mgu9c9c1y5dGIQ((*colonenvP_).retFutUnownX60gensym310560174_);				if (!T32_) goto LA33_;

#line 45 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
				nimln_(45, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim");				reraiseException();			}
			goto LA30_;
			LA33_: ;
			{				Exception* T36_;
#line 47 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
				nimln_(47, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim");
#line 47 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"

#line 47 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
				T36_ = (Exception*)0;				T36_ = getCurrentException();
#line 47 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
				fail__KP9b34veEV0ehqMJglv63VQ((*colonenvP_).retFutUnownX60gensym310560174_, T36_);
			}
			LA30_: ;
			popCurrentException();		}
	}
	if (TM__F2tqCOO6WDiND6xhXZOuUw_8.status != 0) reraiseException();	popFrame();}

#line 4 "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/nim/example_server.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w*, cb__R1wzpMYDao07llKGNJV9aaQ)(tyObject_Request__1Wfxxtqzahm0R6lueM9aQmQ* req) {	tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* result;	tyObject_Env_example_serverdotnim___m15TreKjsI9ax7nUqERmdaQ* colonenv_;	tyObject_Env_asyncmacrodotnim___nDq9c3JWrEMiahPRz1h5tLw* colonenv__2;	tyProc__uz49bJm19cqLWB77G7nLz3FA T1_;	tyProc__HzVCwACFYM9cx9aV62PdjtuA T2_;	nimfr_("cb", "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/ni"
"m/example_server.nim");{	result = (tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w*)0;	colonenv_ = (tyObject_Env_example_serverdotnim___m15TreKjsI9ax7nUqERmdaQ*)0;
#line 235 "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim"
	nimln_(235, "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim");	colonenv_ = (tyObject_Env_example_serverdotnim___m15TreKjsI9ax7nUqERmdaQ*) newObj((&NTI__baZlsAq9c5BaiB74trUvOHw_), sizeof(tyObject_Env_example_serverdotnim___m15TreKjsI9ax7nUqERmdaQ));	(*colonenv_).Sup.m_type = (&NTI__m15TreKjsI9ax7nUqERmdaQ_);
#line 4 "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/nim/example_server.nim"
	nimln_(4, "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/ni"
"m/example_server.nim");	genericAssign((void*)(&(*colonenv_).req1), (void*)req, (&NTI__1Wfxxtqzahm0R6lueM9aQmQ_));
#line 4 "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/nim/example_server.nim"

#line 4 "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/nim/example_server.nim"
	asgnRef((void**) (&(*colonenv_).retFuture2), newFuture__O5FiTIx7b9aJMbTMTl7J2SQ(((NimStringDesc*) &TM__F2tqCOO6WDiND6xhXZOuUw_5)));
#line 17 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
	nimln_(17, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim");	asgnRef((void**) (&(*colonenv_).retFutUnownX60gensym310560174_), (*colonenv_).retFuture2);
#line 19 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
	nimln_(19, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim");	colonenv__2 = (tyObject_Env_asyncmacrodotnim___nDq9c3JWrEMiahPRz1h5tLw*)0;
#line 235 "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim"
	nimln_(235, "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim");	colonenv__2 = (tyObject_Env_asyncmacrodotnim___nDq9c3JWrEMiahPRz1h5tLw*) newObj((&NTI__P9cJvr1z9ajzzZb5SJxD56xA_), sizeof(tyObject_Env_asyncmacrodotnim___nDq9c3JWrEMiahPRz1h5tLw));	(*colonenv__2).Sup.m_type = (&NTI__nDq9c3JWrEMiahPRz1h5tLw_);
#line 187 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
	nimln_(187, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim");	asgnRef((void**) (&(*colonenv__2).colonup_), colonenv_);	nimZeroMem((void*)(&T1_), sizeof(tyProc__uz49bJm19cqLWB77G7nLz3FA));	T1_.ClP_0 = cbIter__mAuTRAkOPFmW9aSKpTLnZWg; T1_.ClE_0 = colonenv__2;	asgnRef((void**) (&(*colonenv_).nameIterVarX60gensym310560183_.ClE_0), T1_.ClE_0);	(*colonenv_).nameIterVarX60gensym310560183_.ClP_0 = T1_.ClP_0;
#line 246 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
	nimln_(246, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim");	nimZeroMem((void*)(&T2_), sizeof(tyProc__HzVCwACFYM9cx9aV62PdjtuA));	T2_.ClP_0 = cbNimAsyncContinue__9bVdb9bX5YIpmecEjobmcpQQ; T2_.ClE_0 = colonenv_;	T2_.ClE_0? T2_.ClP_0(T2_.ClE_0):((TM__F2tqCOO6WDiND6xhXZOuUw_12)(T2_.ClP_0))();

#line 5 "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/nim/example_server.nim"
	nimln_(5, "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/ni"
"m/example_server.nim");
#line 246 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim"
	nimln_(246, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/asyncmacro.nim");	result = (*colonenv_).retFuture2;	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 7 "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/nim/example_server.nim"
N_LIB_PRIVATE N_NIMCALL(void, run_http_server)(void) {	tyObject_AsyncHttpServercolonObjectType___9blhbIPPCWUB8g9b1PZ6GMnw* server;	tyProc__czO9bLH6rWgTeb5AIcTKy5g T1_;	tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* T2_;	nimfr_("run_http_server", "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/ni"
"m/example_server.nim");
#line 8 "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/nim/example_server.nim"
	nimln_(8, "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/ni"
"m/example_server.nim");	echoBinSafe(TM__F2tqCOO6WDiND6xhXZOuUw_2, 1);
#line 9 "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/nim/example_server.nim"
	nimln_(9, "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/ni"
"m/example_server.nim");
#line 9 "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/nim/example_server.nim"
	server = newAsyncHttpServer__3nt12aazkrwWwKRGH9bCj9bw(NIM_TRUE, NIM_FALSE, ((NI) 8388608));
#line 11 "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/nim/example_server.nim"
	nimln_(11, "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/ni"
"m/example_server.nim");
#line 11 "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/nim/example_server.nim"
	nimZeroMem((void*)(&T1_), sizeof(tyProc__czO9bLH6rWgTeb5AIcTKy5g));	T1_.ClP_0 = ((TM__F2tqCOO6WDiND6xhXZOuUw_13) (cb__R1wzpMYDao07llKGNJV9aaQ)); T1_.ClE_0 = NIM_NIL;
#line 11 "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/nim/example_server.nim"
	T2_ = (tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w*)0;	T2_ = serve__PCNVS7VCLMlzsJOLb7Qi9bg(server, ((NU16) 8181), T1_, ((NimStringDesc*) NIM_NIL));
#line 11 "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/nim/example_server.nim"
	waitFor__zz9aVsJN0aTuFUXvzKrFo9cA(T2_);
	popFrame();}

#line 2113 "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim"
static N_INLINE(void, initStackBottomWith)(void* locals) {
#line 2117 "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim"

#line 2117 "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim"
	nimGC_setStackBottom(locals);
}

N_LIB_PRIVATE void PreMainInner(void) {
	stdlib_timesInit000();
	stdlib_osInit000();
	stdlib_asyncfuturesInit000();
	stdlib_nativesocketsInit000();
	stdlib_asyncdispatchInit000();
}

N_LIB_PRIVATE int cmdCount;
N_LIB_PRIVATE char** cmdLine;
N_LIB_PRIVATE char** gEnv;
N_LIB_PRIVATE void PreMain(void) {
	void (*volatile inner)(void);
	inner = PreMainInner;
	systemDatInit000();
	initStackBottomWith((void *)&inner);
	systemInit000();
	stdlib_optionsDatInit000();
	stdlib_timesDatInit000();
	stdlib_osDatInit000();
	stdlib_tablesDatInit000();
	stdlib_heapqueueDatInit000();
	stdlib_dequesDatInit000();
	stdlib_asyncfuturesDatInit000();
	stdlib_monotimesDatInit000();
	stdlib_nativesocketsDatInit000();
	stdlib_netDatInit000();
	stdlib_selectorsDatInit000();
	stdlib_asyncdispatchDatInit000();
	stdlib_asyncnetDatInit000();
	stdlib_uriDatInit000();
	stdlib_httpcoreDatInit000();
	stdlib_asynchttpserverDatInit000();
	example_serverDatInit000();
	(*inner)();
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {

#line 999999 "generated_not_to_break_here"
{
	nimfr_("example_server", "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/ni"
"m/example_server.nim");
#line 14 "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/nim/example_server.nim"
	nimln_(14, "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/ni"
"m/example_server.nim");	echoBinSafe(TM__F2tqCOO6WDiND6xhXZOuUw_14, 1);
#line 15 "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/nim/example_server.nim"
	nimln_(15, "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/ni"
"m/example_server.nim");
#line 15 "/home/elcritch/projects/pt/third-party/esp32_nim_net_example/nim/example_server.nim"
	run_http_server();
	popFrame();}
}

N_LIB_PRIVATE N_NIMCALL(void, example_serverDatInit000)(void) {

#line 999999 "generated_not_to_break_here"

/* section: NIM_merge_TYPE_INIT1 */
static TNimNode* TM__F2tqCOO6WDiND6xhXZOuUw_4_5[5];
static TNimNode* TM__F2tqCOO6WDiND6xhXZOuUw_6_4[4];
static TNimNode TM__F2tqCOO6WDiND6xhXZOuUw_0[11];
/* section: NIM_merge_TYPE_INIT3 */
NTI__m15TreKjsI9ax7nUqERmdaQ_.size = sizeof(tyObject_Env_example_serverdotnim___m15TreKjsI9ax7nUqERmdaQ);
NTI__m15TreKjsI9ax7nUqERmdaQ_.align = NIM_ALIGNOF(tyObject_Env_example_serverdotnim___m15TreKjsI9ax7nUqERmdaQ);
NTI__m15TreKjsI9ax7nUqERmdaQ_.kind = 17;
NTI__m15TreKjsI9ax7nUqERmdaQ_.base = (&NTI__ytyiCJqK439aF9cIibuRVpAg_);
TM__F2tqCOO6WDiND6xhXZOuUw_4_5[0] = &TM__F2tqCOO6WDiND6xhXZOuUw_0[1];
TM__F2tqCOO6WDiND6xhXZOuUw_0[1].kind = 1;
TM__F2tqCOO6WDiND6xhXZOuUw_0[1].offset = offsetof(tyObject_Env_example_serverdotnim___m15TreKjsI9ax7nUqERmdaQ, colonstate_);
TM__F2tqCOO6WDiND6xhXZOuUw_0[1].typ = (&NTI__xHTZrq9aYs6boc9bCba0JbpQ_);
TM__F2tqCOO6WDiND6xhXZOuUw_0[1].name = ":state";
TM__F2tqCOO6WDiND6xhXZOuUw_4_5[1] = &TM__F2tqCOO6WDiND6xhXZOuUw_0[2];
TM__F2tqCOO6WDiND6xhXZOuUw_0[2].kind = 1;
TM__F2tqCOO6WDiND6xhXZOuUw_0[2].offset = offsetof(tyObject_Env_example_serverdotnim___m15TreKjsI9ax7nUqERmdaQ, req1);
TM__F2tqCOO6WDiND6xhXZOuUw_0[2].typ = (&NTI__1Wfxxtqzahm0R6lueM9aQmQ_);
TM__F2tqCOO6WDiND6xhXZOuUw_0[2].name = "req1";
TM__F2tqCOO6WDiND6xhXZOuUw_4_5[2] = &TM__F2tqCOO6WDiND6xhXZOuUw_0[3];
TM__F2tqCOO6WDiND6xhXZOuUw_0[3].kind = 1;
TM__F2tqCOO6WDiND6xhXZOuUw_0[3].offset = offsetof(tyObject_Env_example_serverdotnim___m15TreKjsI9ax7nUqERmdaQ, retFuture2);
TM__F2tqCOO6WDiND6xhXZOuUw_0[3].typ = (&NTI__TjokxNjmnZmr9bygVDVC9bvg_);
TM__F2tqCOO6WDiND6xhXZOuUw_0[3].name = "retFuture2";
TM__F2tqCOO6WDiND6xhXZOuUw_4_5[3] = &TM__F2tqCOO6WDiND6xhXZOuUw_0[4];
TM__F2tqCOO6WDiND6xhXZOuUw_0[4].kind = 1;
TM__F2tqCOO6WDiND6xhXZOuUw_0[4].offset = offsetof(tyObject_Env_example_serverdotnim___m15TreKjsI9ax7nUqERmdaQ, nameIterVarX60gensym310560183_);
TM__F2tqCOO6WDiND6xhXZOuUw_0[4].typ = (&NTI__uz49bJm19cqLWB77G7nLz3FA_);
TM__F2tqCOO6WDiND6xhXZOuUw_0[4].name = "nameIterVar`gensym310560183";
TM__F2tqCOO6WDiND6xhXZOuUw_4_5[4] = &TM__F2tqCOO6WDiND6xhXZOuUw_0[5];
TM__F2tqCOO6WDiND6xhXZOuUw_0[5].kind = 1;
TM__F2tqCOO6WDiND6xhXZOuUw_0[5].offset = offsetof(tyObject_Env_example_serverdotnim___m15TreKjsI9ax7nUqERmdaQ, retFutUnownX60gensym310560174_);
TM__F2tqCOO6WDiND6xhXZOuUw_0[5].typ = (&NTI__TjokxNjmnZmr9bygVDVC9bvg_);
TM__F2tqCOO6WDiND6xhXZOuUw_0[5].name = "retFutUnown`gensym310560174";
TM__F2tqCOO6WDiND6xhXZOuUw_0[0].len = 5; TM__F2tqCOO6WDiND6xhXZOuUw_0[0].kind = 2; TM__F2tqCOO6WDiND6xhXZOuUw_0[0].sons = &TM__F2tqCOO6WDiND6xhXZOuUw_4_5[0];
NTI__m15TreKjsI9ax7nUqERmdaQ_.node = &TM__F2tqCOO6WDiND6xhXZOuUw_0[0];
NTI__baZlsAq9c5BaiB74trUvOHw_.size = sizeof(tyObject_Env_example_serverdotnim___m15TreKjsI9ax7nUqERmdaQ*);
NTI__baZlsAq9c5BaiB74trUvOHw_.align = NIM_ALIGNOF(tyObject_Env_example_serverdotnim___m15TreKjsI9ax7nUqERmdaQ*);
NTI__baZlsAq9c5BaiB74trUvOHw_.kind = 22;
NTI__baZlsAq9c5BaiB74trUvOHw_.base = (&NTI__m15TreKjsI9ax7nUqERmdaQ_);
NTI__baZlsAq9c5BaiB74trUvOHw_.marker = Marker_tyRef__baZlsAq9c5BaiB74trUvOHw;
NTI__nDq9c3JWrEMiahPRz1h5tLw_.size = sizeof(tyObject_Env_asyncmacrodotnim___nDq9c3JWrEMiahPRz1h5tLw);
NTI__nDq9c3JWrEMiahPRz1h5tLw_.align = NIM_ALIGNOF(tyObject_Env_asyncmacrodotnim___nDq9c3JWrEMiahPRz1h5tLw);
NTI__nDq9c3JWrEMiahPRz1h5tLw_.kind = 17;
NTI__nDq9c3JWrEMiahPRz1h5tLw_.base = (&NTI__ytyiCJqK439aF9cIibuRVpAg_);
TM__F2tqCOO6WDiND6xhXZOuUw_6_4[0] = &TM__F2tqCOO6WDiND6xhXZOuUw_0[7];
TM__F2tqCOO6WDiND6xhXZOuUw_0[7].kind = 1;
TM__F2tqCOO6WDiND6xhXZOuUw_0[7].offset = offsetof(tyObject_Env_asyncmacrodotnim___nDq9c3JWrEMiahPRz1h5tLw, colonstate_);
TM__F2tqCOO6WDiND6xhXZOuUw_0[7].typ = (&NTI__xHTZrq9aYs6boc9bCba0JbpQ_);
TM__F2tqCOO6WDiND6xhXZOuUw_0[7].name = ":state";
TM__F2tqCOO6WDiND6xhXZOuUw_6_4[1] = &TM__F2tqCOO6WDiND6xhXZOuUw_0[8];
TM__F2tqCOO6WDiND6xhXZOuUw_0[8].kind = 1;
TM__F2tqCOO6WDiND6xhXZOuUw_0[8].offset = offsetof(tyObject_Env_asyncmacrodotnim___nDq9c3JWrEMiahPRz1h5tLw, internalTmpFutureX60gensym31056023X60gensym310600321_);
TM__F2tqCOO6WDiND6xhXZOuUw_0[8].typ = (&NTI__G3WIkXk4MjMLVyyUid6IEw_);
TM__F2tqCOO6WDiND6xhXZOuUw_0[8].name = "internalTmpFuture`gensym31056023`gensym310600321";
TM__F2tqCOO6WDiND6xhXZOuUw_6_4[2] = &TM__F2tqCOO6WDiND6xhXZOuUw_0[9];
TM__F2tqCOO6WDiND6xhXZOuUw_0[9].kind = 1;
TM__F2tqCOO6WDiND6xhXZOuUw_0[9].offset = offsetof(tyObject_Env_asyncmacrodotnim___nDq9c3JWrEMiahPRz1h5tLw, colonup_);
TM__F2tqCOO6WDiND6xhXZOuUw_0[9].typ = (&NTI__baZlsAq9c5BaiB74trUvOHw_);
TM__F2tqCOO6WDiND6xhXZOuUw_0[9].name = ":up";
TM__F2tqCOO6WDiND6xhXZOuUw_6_4[3] = &TM__F2tqCOO6WDiND6xhXZOuUw_0[10];
TM__F2tqCOO6WDiND6xhXZOuUw_0[10].kind = 1;
TM__F2tqCOO6WDiND6xhXZOuUw_0[10].offset = offsetof(tyObject_Env_asyncmacrodotnim___nDq9c3JWrEMiahPRz1h5tLw, result3);
TM__F2tqCOO6WDiND6xhXZOuUw_0[10].typ = (&NTI__G3WIkXk4MjMLVyyUid6IEw_);
TM__F2tqCOO6WDiND6xhXZOuUw_0[10].name = "result3";
TM__F2tqCOO6WDiND6xhXZOuUw_0[6].len = 4; TM__F2tqCOO6WDiND6xhXZOuUw_0[6].kind = 2; TM__F2tqCOO6WDiND6xhXZOuUw_0[6].sons = &TM__F2tqCOO6WDiND6xhXZOuUw_6_4[0];
NTI__nDq9c3JWrEMiahPRz1h5tLw_.node = &TM__F2tqCOO6WDiND6xhXZOuUw_0[6];
NTI__P9cJvr1z9ajzzZb5SJxD56xA_.size = sizeof(tyObject_Env_asyncmacrodotnim___nDq9c3JWrEMiahPRz1h5tLw*);
NTI__P9cJvr1z9ajzzZb5SJxD56xA_.align = NIM_ALIGNOF(tyObject_Env_asyncmacrodotnim___nDq9c3JWrEMiahPRz1h5tLw*);
NTI__P9cJvr1z9ajzzZb5SJxD56xA_.kind = 22;
NTI__P9cJvr1z9ajzzZb5SJxD56xA_.base = (&NTI__nDq9c3JWrEMiahPRz1h5tLw_);
NTI__P9cJvr1z9ajzzZb5SJxD56xA_.marker = Marker_tyRef__P9cJvr1z9ajzzZb5SJxD56xA;
}

