/* Generated by Nim Compiler v1.3.3 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <fcntl.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_PROC_HEADERS */
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);

/* section: NIM_merge_VARS */
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;

/* section: NIM_merge_PROCS */

#line 549 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 550 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 550 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA3_;

#line 551 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 554 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 554 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 556 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 557 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 558 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 558 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 558 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 558 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}

#line 85 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 86 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}

#line 326 "/home/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, setInheritable__avyDiy1HdQrfaD3Ql9b63EQ)(int f, NIM_BOOL inheritable) {	NIM_BOOL result;	int flags;	int T10_;	nimfr_("setInheritable", "/home/elcritch/.asdf/installs/nim/devel/lib/system/io.nim");{	result = (NIM_BOOL)0;
#line 336 "/home/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
	nimln_(336, "/home/elcritch/.asdf/installs/nim/devel/lib/system/io.nim");
#line 336 "/home/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
	flags = fcntl(f, F_GETFD);
#line 337 "/home/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
	nimln_(337, "/home/elcritch/.asdf/installs/nim/devel/lib/system/io.nim");	{
#line 337 "/home/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
		if (!(flags == ((NI32) -1))) goto LA3_;

#line 338 "/home/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
		nimln_(338, "/home/elcritch/.asdf/installs/nim/devel/lib/system/io.nim");
#line 338 "/home/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
		result = NIM_FALSE;		goto BeforeRet_;
	}
	LA3_: ;

#line 339 "/home/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
	nimln_(339, "/home/elcritch/.asdf/installs/nim/devel/lib/system/io.nim");
#line 339 "/home/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
	{		if (!inheritable) goto LA7_;

#line 339 "/home/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"

#line 339 "/home/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
		flags = (NI32)(flags & (NI32)((NU32) ~(FD_CLOEXEC)));	}
	goto LA5_;
	LA7_: ;
	{
#line 339 "/home/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
		flags = (NI32)(flags | FD_CLOEXEC);	}
	LA5_: ;

#line 340 "/home/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
	nimln_(340, "/home/elcritch/.asdf/installs/nim/devel/lib/system/io.nim");
#line 340 "/home/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"

#line 340 "/home/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"

#line 340 "/home/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"

#line 340 "/home/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
	T10_ = (int)0;	T10_ = fcntl(f, F_SETFD, flags);	result = !((T10_ == ((NI32) -1)));	}BeforeRet_: ;
	popFrame();	return result;}
