/* Generated by Nim Compiler v1.3.3 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <pthread.h>
#include <sys/types.h>
                          #include <pthread.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
#define nimfr_(x, y)
#define nimln_(x, y)

/* section: NIM_merge_FORWARD_TYPES */
typedef struct tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw;
typedef struct tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg;

/* section: NIM_merge_TYPES */
struct tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw {tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg* head;
tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg* tail;
pthread_mutex_t lock;
};
typedef void* tyArray__Rrw59cMvNu8cDA9cQDh4v2oA[100];
struct tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg {tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg* next;
NI dataLen;
tyArray__Rrw59cMvNu8cDA9cQDh4v2oA d;
};

/* section: NIM_merge_PROC_HEADERS */
static N_INLINE(void, initLock__Mz9ax9a7rBFxTQq0g0dLnxAwlocks)(pthread_mutex_t* lock);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);

/* section: NIM_merge_VARS */
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;

/* section: NIM_merge_PROCS */

#line 27 "/home/elcritch/.asdf/installs/nim/devel/lib/core/locks.nim"
static N_INLINE(void, initLock__Mz9ax9a7rBFxTQq0g0dLnxAwlocks)(pthread_mutex_t* lock) {
#line 29 "/home/elcritch/.asdf/installs/nim/devel/lib/core/locks.nim"

#line 29 "/home/elcritch/.asdf/installs/nim/devel/lib/core/locks.nim"
	pthread_mutex_init(lock, NIM_NIL);
}

#line 424 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 425 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);	return result;}

#line 78 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/collections/sharedlist.nim"
N_LIB_PRIVATE N_NIMCALL(void, init__rlyb6Y54ONML4HcId0P2OA)(tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw* t) {NIM_BOOL* nimErr_;{nimErr_ = nimErrorFlag();
#line 79 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/collections/sharedlist.nim"

#line 79 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/collections/sharedlist.nim"
	initLock__Mz9ax9a7rBFxTQq0g0dLnxAwlocks((&(*t).lock));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 80 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/collections/sharedlist.nim"
	(*t).head = NIM_NIL;
#line 81 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/collections/sharedlist.nim"
	(*t).tail = NIM_NIL;	}BeforeRet_: ;
}
