/* Generated by Nim Compiler v1.3.5 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_SocketImpl__aIhANOOoETolVz9cccNO9cRQ tyObject_SocketImpl__aIhANOOoETolVz9cccNO9cRQ;

/* section: NIM_merge_TYPES */
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};
typedef NIM_CHAR tyArray__QQGLPNVVwLhYjkngqAxXQQ[4001];
typedef NU8 tyEnum_Domain__Q79bEtFARvq0ekDNtvj3Vqg;
typedef NU8 tyEnum_SockType__NQT1bItGG2X9byGdrWX7ujw;
typedef NU8 tyEnum_Protocol__dqJ1OqRGclxIMMdSLRzzXg;
struct tyObject_SocketImpl__aIhANOOoETolVz9cccNO9cRQ {int fd;
NIM_BOOL isBuffered;
tyArray__QQGLPNVVwLhYjkngqAxXQQ buffer;
NI currPos;
NI bufLen;
NI32 lastError;
tyEnum_Domain__Q79bEtFARvq0ekDNtvj3Vqg domain;
tyEnum_SockType__NQT1bItGG2X9byGdrWX7ujw sockType;
tyEnum_Protocol__dqJ1OqRGclxIMMdSLRzzXg protocol;
};

/* section: NIM_merge_PROC_HEADERS */
N_LIB_PRIVATE N_NIMCALL(void, eqsink___aBBXmHFBEivKqERloP6zmA)(NimStringV2* dest, NimStringV2 src);
N_LIB_PRIVATE N_NIMCALL(void, reprObject__rpxzovMTAQ5iPPdHLFpTcQ)(NimStringV2* res, tyObject_SocketImpl__aIhANOOoETolVz9cccNO9cRQ* x);
N_LIB_PRIVATE N_NIMCALL(void, nimAddCharV1)(NimStringV2* s_0, NIM_CHAR c);
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source, NI size_0);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size_0);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a, NI b, NI* res);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_0, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_0, NI addlen);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nimIntToStr)(NI x);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nimBoolToStr)(NIM_BOOL x);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, repr__zTDOZf2oxS0Z1goEAVDdVQ)(tyArray__QQGLPNVVwLhYjkngqAxXQQ x);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, collectionToRepr__6yT8kL9cCF0SQSewTvhI5Pw)(tyArray__QQGLPNVVwLhYjkngqAxXQQ x, NimStringV2 prefix, NimStringV2 separator, NimStringV2 suffix);
N_LIB_PRIVATE N_NIMCALL(void, eq___aBBXmHFBEivKqERloP6zmA_2)(NimStringV2* dest, NimStringV2 src);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, repr__Yw2I5ryns5wIGJR9ct8NWHg)(NIM_CHAR x);
static N_INLINE(void, appendChar)(NimStringV2* dest, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nimCharToStr)(NIM_CHAR x);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___Ak5SZt3EVWRKrcMjBNQjBA)(tyEnum_Domain__Q79bEtFARvq0ekDNtvj3Vqg e);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___cm8O0zVbDQ8zSf631WHXOw)(tyEnum_SockType__NQT1bItGG2X9byGdrWX7ujw e);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___NC3vOXFMeN9av3LzEF7uXbg)(tyEnum_Protocol__dqJ1OqRGclxIMMdSLRzzXg e);

/* section: NIM_merge_DATA */
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__bQ89bat3hUkmJB4hVh79bf4w_2 = { 3 | NIM_STRLIT_FLAG, "nil" };
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_3 = {3, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_2};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__bQ89bat3hUkmJB4hVh79bf4w_4 = { 6 | NIM_STRLIT_FLAG, "Socket" };
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_5 = {6, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_4};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__bQ89bat3hUkmJB4hVh79bf4w_6 = { 2 | NIM_STRLIT_FLAG, ", " };
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_7 = {2, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_6};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__bQ89bat3hUkmJB4hVh79bf4w_10 = { 2 | NIM_STRLIT_FLAG, "fd" };
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_11 = {2, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_10};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__bQ89bat3hUkmJB4hVh79bf4w_12 = { 2 | NIM_STRLIT_FLAG, ": " };
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_13 = {2, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_12};
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_14 = {2, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_6};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__bQ89bat3hUkmJB4hVh79bf4w_15 = { 10 | NIM_STRLIT_FLAG, "isBuffered" };
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_16 = {10, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_15};
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_17 = {2, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_12};
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_18 = {2, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_6};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__bQ89bat3hUkmJB4hVh79bf4w_19 = { 6 | NIM_STRLIT_FLAG, "buffer" };
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_20 = {6, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_19};
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_21 = {2, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_12};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__bQ89bat3hUkmJB4hVh79bf4w_25 = { 1 | NIM_STRLIT_FLAG, "[" };
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_26 = {1, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_25};
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_27 = {2, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_6};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__bQ89bat3hUkmJB4hVh79bf4w_28 = { 1 | NIM_STRLIT_FLAG, "]" };
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_29 = {1, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_28};
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_30 = {2, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_6};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__bQ89bat3hUkmJB4hVh79bf4w_31 = { 7 | NIM_STRLIT_FLAG, "currPos" };
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_32 = {7, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_31};
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_33 = {2, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_12};
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_34 = {2, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_6};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__bQ89bat3hUkmJB4hVh79bf4w_35 = { 6 | NIM_STRLIT_FLAG, "bufLen" };
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_36 = {6, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_35};
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_37 = {2, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_12};
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_38 = {2, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_6};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__bQ89bat3hUkmJB4hVh79bf4w_39 = { 9 | NIM_STRLIT_FLAG, "lastError" };
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_40 = {9, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_39};
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_41 = {2, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_12};
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_42 = {2, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_6};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__bQ89bat3hUkmJB4hVh79bf4w_43 = { 6 | NIM_STRLIT_FLAG, "domain" };
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_44 = {6, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_43};
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_45 = {2, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_12};
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_46 = {2, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_6};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__bQ89bat3hUkmJB4hVh79bf4w_47 = { 8 | NIM_STRLIT_FLAG, "sockType" };
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_48 = {8, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_47};
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_49 = {2, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_12};
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_50 = {2, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_6};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__bQ89bat3hUkmJB4hVh79bf4w_51 = { 8 | NIM_STRLIT_FLAG, "protocol" };
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_52 = {8, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_51};
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_53 = {2, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_12};

/* section: NIM_merge_VARS */
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;

/* section: NIM_merge_PROCS */

#line 11 "/home/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size_0) {	void* T1_;
#line 13 "/home/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"

#line 13 "/home/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memcpy(dest, source, ((size_t) (size_0)));}

#line 2138 "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim"
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source, NI size_0) {
#line 2139 "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim"

#line 2139 "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim"
	nimCopyMem(dest, source, size_0);
}

#line 52 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
static N_INLINE(NIM_BOOL, nimAddInt)(NI a, NI b, NI* res) {	NIM_BOOL result;	NI r;	result = (NIM_BOOL)0;
#line 46 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 46 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
	r = ((NI) ((NU)((NU32)(((NU) (a))) + (NU32)(((NU) (b))))));
#line 47 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
	{		NIM_BOOL T3_;
#line 47 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (NIM_BOOL)0;
#line 47 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 47 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (((NI) 0) <= (NI)(r ^ a));		if (T3_) goto LA4_;

#line 47 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 47 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (((NI) 0) <= (NI)(r ^ b));		LA4_: ;
		if (!T3_) goto LA5_;

#line 48 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		(*res) = r;	}
	goto LA1_;
	LA5_: ;
	{
#line 50 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		result = NIM_TRUE;	}
	LA1_: ;
	return result;}

#line 80 "/home/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src) {{
#line 81 "/home/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
	{		NI TM__bQ89bat3hUkmJB4hVh79bf4w_8;		NI TM__bQ89bat3hUkmJB4hVh79bf4w_9;
#line 81 "/home/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
		if (!(((NI) 0) < src.len)) goto LA3_;

#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"

#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
		if (nimAddInt(src.len, ((NI) 1), &TM__bQ89bat3hUkmJB4hVh79bf4w_8)) { raiseOverflow(); goto BeforeRet_;};		if (((NI)(TM__bQ89bat3hUkmJB4hVh79bf4w_8)) < ((NI) 0) || ((NI)(TM__bQ89bat3hUkmJB4hVh79bf4w_8)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__bQ89bat3hUkmJB4hVh79bf4w_8), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;}
#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
		copyMem__M04YC71iJg1N7gBF3HZTngsystem(((void*) ((&(*(*dest).p).data[(*dest).len]))), ((void*) ((&(*src.p).data[((NI) 0)]))), ((NI) ((NI)(TM__bQ89bat3hUkmJB4hVh79bf4w_8))));

#line 84 "/home/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
		if (nimAddInt((*dest).len, src.len, &TM__bQ89bat3hUkmJB4hVh79bf4w_9)) { raiseOverflow(); goto BeforeRet_;};		(*dest).len = (NI)(TM__bQ89bat3hUkmJB4hVh79bf4w_9);	}
	LA3_: ;
	}BeforeRet_: ;
}

#line 86 "/home/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
static N_INLINE(void, appendChar)(NimStringV2* dest, NIM_CHAR c) {	NI TM__bQ89bat3hUkmJB4hVh79bf4w_22;	NI TM__bQ89bat3hUkmJB4hVh79bf4w_23;{
#line 87 "/home/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
	(*(*dest).p).data[(*dest).len] = c;
#line 88 "/home/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
	if (nimAddInt((*dest).len, ((NI) 1), &TM__bQ89bat3hUkmJB4hVh79bf4w_22)) { raiseOverflow(); goto BeforeRet_;};
#line 88 "/home/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
	(*(*dest).p).data[(NI)(TM__bQ89bat3hUkmJB4hVh79bf4w_22)] = 0;
#line 89 "/home/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
	if (nimAddInt((*dest).len, ((NI) 1), &TM__bQ89bat3hUkmJB4hVh79bf4w_23)) { raiseOverflow(); goto BeforeRet_;};	(*dest).len = (NI)(TM__bQ89bat3hUkmJB4hVh79bf4w_23);	}BeforeRet_: ;
}

#line 424 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 425 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);	return result;}

#line 549 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s_0) {
#line 550 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 550 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA3_;

#line 551 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s_0).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 554 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 554 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s_0).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 556 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	(*s_0).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 557 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s_0;
#line 558 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 558 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!((*s_0).calldepth == ((NI16) 2000))) goto LA8_;

#line 558 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 558 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}

#line 85 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 86 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}

#line 30 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringV2, repr__Yw2I5ryns5wIGJR9ct8NWHg)(NIM_CHAR x) {	NimStringV2 result;	NimStringV2 colontmpD_;	NimStringV2 T2_;	NimStringV2 T3_;NIM_BOOL* nimErr_;	nimfr_("repr", "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");{nimErr_ = nimErrorFlag();	result.len = 0; result.p = NIM_NIL;	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
#line 36 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(36, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 36 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	T2_.len = 0; T2_.p = NIM_NIL;
#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	nimln_(49, "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 36 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(36, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	T3_.len = 0; T3_.p = NIM_NIL;	T3_ = nimCharToStr(x);
#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	nimln_(49, "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");	eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD_), T3_);
	T2_ = rawNewString(colontmpD_.len + 2);appendChar((&T2_), 39);appendString((&T2_), colontmpD_);appendChar((&T2_), 39);	result = T2_;	{		LA1_:;	}
	{
#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();	return result;}

#line 118 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringV2, collectionToRepr__6yT8kL9cCF0SQSewTvhI5Pw)(tyArray__QQGLPNVVwLhYjkngqAxXQQ x, NimStringV2 prefix, NimStringV2 separator, NimStringV2 suffix) {	NimStringV2 result;	NimStringV2 colontmpD_;	NIM_BOOL firstElement;NIM_BOOL* nimErr_;	nimfr_("collectionToRepr", "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");{nimErr_ = nimErrorFlag();	result.len = 0; result.p = NIM_NIL;	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	nimln_(49, "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	eq___aBBXmHFBEivKqERloP6zmA_2((&result), prefix);

#line 120 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(120, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	firstElement = NIM_TRUE;	{		NIM_CHAR value_1;		NI i_1;		value_1 = (NIM_CHAR)0;
#line 42 "/home/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
		nimln_(42, "/home/elcritch/.asdf/installs/nim/devel/lib/system/iterators.ni"
"m");		i_1 = ((NI) 0);
#line 43 "/home/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
		nimln_(43, "/home/elcritch/.asdf/installs/nim/devel/lib/system/iterators.ni"
"m");		{
#line 43 "/home/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
			if (!(((NI) (i_1)) <= ((NI) 4000))) goto LA5_;
			{
#line 44 "/home/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
				nimln_(44, "/home/elcritch/.asdf/installs/nim/devel/lib/system/iterators.ni"
"m");				while (1) {					NimStringV2 T14_;					NI TM__bQ89bat3hUkmJB4hVh79bf4w_24;
#line 121 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
					nimln_(121, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");					value_1 = x[(i_1)- 0];
#line 122 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
					nimln_(122, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");					{						if (!firstElement) goto LA11_;

#line 123 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
						nimln_(123, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");						firstElement = NIM_FALSE;					}
					goto LA9_;
					LA11_: ;
					{
#line 125 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
						nimln_(125, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");						prepareAdd((&result), separator.len + 0);appendString((&result), separator);					}
					LA9_: ;

#line 126 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
					nimln_(126, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
					nimln_(49, "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 126 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
					nimln_(126, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 126 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
					T14_.len = 0; T14_.p = NIM_NIL;					T14_ = repr__Yw2I5ryns5wIGJR9ct8NWHg(value_1);					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
					nimln_(49, "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");					eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD_), T14_);
					prepareAdd((&result), colontmpD_.len + 0);appendString((&result), colontmpD_);
#line 46 "/home/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
					nimln_(46, "/home/elcritch/.asdf/installs/nim/devel/lib/system/iterators.ni"
"m");					{
#line 46 "/home/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
						if (!(((NI) 4000) <= ((NI) (i_1)))) goto LA17_;

#line 46 "/home/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
						goto LA7;
					}
					LA17_: ;

#line 47 "/home/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
					nimln_(47, "/home/elcritch/.asdf/installs/nim/devel/lib/system/iterators.ni"
"m");					if (nimAddInt(i_1, ((NI) 1), &TM__bQ89bat3hUkmJB4hVh79bf4w_24)) { raiseOverflow(); goto LA1_;};					if (TM__bQ89bat3hUkmJB4hVh79bf4w_24 < 0 || TM__bQ89bat3hUkmJB4hVh79bf4w_24 > 4000){ raiseOverflow(); goto LA1_;}					i_1 = (NI)(TM__bQ89bat3hUkmJB4hVh79bf4w_24);				}
			} LA7: ;
		}
		LA5_: ;
	}

#line 127 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(127, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	prepareAdd((&result), suffix.len + 0);appendString((&result), suffix);	{		LA1_:;	}
	{
#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		nimln_(49, "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();	return result;}

#line 155 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringV2, repr__zTDOZf2oxS0Z1goEAVDdVQ)(tyArray__QQGLPNVVwLhYjkngqAxXQQ x) {	NimStringV2 result;NIM_BOOL* nimErr_;	nimfr_("repr", "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");{nimErr_ = nimErrorFlag();	result.len = 0; result.p = NIM_NIL;
#line 157 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(157, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 157 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	result = collectionToRepr__6yT8kL9cCF0SQSewTvhI5Pw(x, TM__bQ89bat3hUkmJB4hVh79bf4w_26, TM__bQ89bat3hUkmJB4hVh79bf4w_27, TM__bQ89bat3hUkmJB4hVh79bf4w_29);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();	return result;}

#line 76 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
N_LIB_PRIVATE N_NIMCALL(void, reprObject__rpxzovMTAQ5iPPdHLFpTcQ)(NimStringV2* res, tyObject_SocketImpl__aIhANOOoETolVz9cccNO9cRQ* x) {	NimStringV2 colontmpD_;	NimStringV2 colontmpD__2;	NimStringV2 colontmpD__3;	NimStringV2 colontmpD__4;	NimStringV2 colontmpD__5;	NimStringV2 colontmpD__6;	NimStringV2 colontmpD__7;	NimStringV2 colontmpD__8;	NimStringV2 colontmpD__9;	NIM_BOOL firstElement;	NimStringV2 T6_;	NimStringV2 T11_;	NimStringV2 T16_;	NimStringV2 T21_;	NimStringV2 T26_;	NimStringV2 T31_;	NimStringV2 T36_;	NimStringV2 T41_;	NimStringV2 T46_;NIM_BOOL* nimErr_;	nimfr_("reprObject", "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");{nimErr_ = nimErrorFlag();	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;	colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;	colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;	colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;	colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;	colontmpD__7.len = 0; colontmpD__7.p = NIM_NIL;	colontmpD__8.len = 0; colontmpD__8.p = NIM_NIL;	colontmpD__9.len = 0; colontmpD__9.p = NIM_NIL;
#line 77 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(77, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	nimAddCharV1((&(*res)), 40);
#line 78 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(78, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	firstElement = NIM_TRUE;
#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(83, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	{
#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		if (!!(firstElement)) goto LA4_;

#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		prepareAdd((&(*res)), 2);appendString((&(*res)), TM__bQ89bat3hUkmJB4hVh79bf4w_7);	}
	LA4_: ;

#line 85 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(85, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	prepareAdd((&(*res)), 2);appendString((&(*res)), TM__bQ89bat3hUkmJB4hVh79bf4w_11);
#line 86 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(86, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	prepareAdd((&(*res)), 2);appendString((&(*res)), TM__bQ89bat3hUkmJB4hVh79bf4w_13);
#line 89 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(89, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	nimln_(49, "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 89 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(89, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	T6_.len = 0; T6_.p = NIM_NIL;	T6_ = nimIntToStr(((NI) ((*x).fd)));
#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	nimln_(49, "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");	eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD_), T6_);
	prepareAdd((&(*res)), colontmpD_.len + 0);appendString((&(*res)), colontmpD_);
#line 90 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(90, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	firstElement = NIM_FALSE;
#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(83, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	{
#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		if (!!(firstElement)) goto LA9_;

#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		prepareAdd((&(*res)), 2);appendString((&(*res)), TM__bQ89bat3hUkmJB4hVh79bf4w_14);	}
	LA9_: ;

#line 85 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(85, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	prepareAdd((&(*res)), 10);appendString((&(*res)), TM__bQ89bat3hUkmJB4hVh79bf4w_16);
#line 86 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(86, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	prepareAdd((&(*res)), 2);appendString((&(*res)), TM__bQ89bat3hUkmJB4hVh79bf4w_17);
#line 89 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(89, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	nimln_(49, "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 89 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(89, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	T11_.len = 0; T11_.p = NIM_NIL;	T11_ = nimBoolToStr((*x).isBuffered);
#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	nimln_(49, "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");	eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD__2), T11_);
	prepareAdd((&(*res)), colontmpD__2.len + 0);appendString((&(*res)), colontmpD__2);
#line 90 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(90, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	firstElement = NIM_FALSE;
#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(83, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	{
#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		if (!!(firstElement)) goto LA14_;

#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		prepareAdd((&(*res)), 2);appendString((&(*res)), TM__bQ89bat3hUkmJB4hVh79bf4w_18);	}
	LA14_: ;

#line 85 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(85, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	prepareAdd((&(*res)), 6);appendString((&(*res)), TM__bQ89bat3hUkmJB4hVh79bf4w_20);
#line 86 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(86, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	prepareAdd((&(*res)), 2);appendString((&(*res)), TM__bQ89bat3hUkmJB4hVh79bf4w_21);
#line 89 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(89, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	nimln_(49, "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 89 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(89, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 89 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	T16_.len = 0; T16_.p = NIM_NIL;	T16_ = repr__zTDOZf2oxS0Z1goEAVDdVQ((*x).buffer);	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	nimln_(49, "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");	eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD__3), T16_);
	prepareAdd((&(*res)), colontmpD__3.len + 0);appendString((&(*res)), colontmpD__3);
#line 90 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(90, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	firstElement = NIM_FALSE;
#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(83, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	{
#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		if (!!(firstElement)) goto LA19_;

#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		prepareAdd((&(*res)), 2);appendString((&(*res)), TM__bQ89bat3hUkmJB4hVh79bf4w_30);	}
	LA19_: ;

#line 85 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(85, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	prepareAdd((&(*res)), 7);appendString((&(*res)), TM__bQ89bat3hUkmJB4hVh79bf4w_32);
#line 86 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(86, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	prepareAdd((&(*res)), 2);appendString((&(*res)), TM__bQ89bat3hUkmJB4hVh79bf4w_33);
#line 89 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(89, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	nimln_(49, "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 89 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(89, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	T21_.len = 0; T21_.p = NIM_NIL;	T21_ = nimIntToStr((*x).currPos);
#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	nimln_(49, "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");	eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD__4), T21_);
	prepareAdd((&(*res)), colontmpD__4.len + 0);appendString((&(*res)), colontmpD__4);
#line 90 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(90, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	firstElement = NIM_FALSE;
#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(83, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	{
#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		if (!!(firstElement)) goto LA24_;

#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		prepareAdd((&(*res)), 2);appendString((&(*res)), TM__bQ89bat3hUkmJB4hVh79bf4w_34);	}
	LA24_: ;

#line 85 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(85, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	prepareAdd((&(*res)), 6);appendString((&(*res)), TM__bQ89bat3hUkmJB4hVh79bf4w_36);
#line 86 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(86, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	prepareAdd((&(*res)), 2);appendString((&(*res)), TM__bQ89bat3hUkmJB4hVh79bf4w_37);
#line 89 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(89, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	nimln_(49, "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 89 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(89, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	T26_.len = 0; T26_.p = NIM_NIL;	T26_ = nimIntToStr((*x).bufLen);
#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	nimln_(49, "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");	eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD__5), T26_);
	prepareAdd((&(*res)), colontmpD__5.len + 0);appendString((&(*res)), colontmpD__5);
#line 90 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(90, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	firstElement = NIM_FALSE;
#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(83, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	{
#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		if (!!(firstElement)) goto LA29_;

#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		prepareAdd((&(*res)), 2);appendString((&(*res)), TM__bQ89bat3hUkmJB4hVh79bf4w_38);	}
	LA29_: ;

#line 85 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(85, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	prepareAdd((&(*res)), 9);appendString((&(*res)), TM__bQ89bat3hUkmJB4hVh79bf4w_40);
#line 86 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(86, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	prepareAdd((&(*res)), 2);appendString((&(*res)), TM__bQ89bat3hUkmJB4hVh79bf4w_41);
#line 89 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(89, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	nimln_(49, "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 89 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(89, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	T31_.len = 0; T31_.p = NIM_NIL;	T31_ = nimIntToStr(((NI) ((*x).lastError)));
#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	nimln_(49, "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");	eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD__6), T31_);
	prepareAdd((&(*res)), colontmpD__6.len + 0);appendString((&(*res)), colontmpD__6);
#line 90 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(90, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	firstElement = NIM_FALSE;
#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(83, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	{
#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		if (!!(firstElement)) goto LA34_;

#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		prepareAdd((&(*res)), 2);appendString((&(*res)), TM__bQ89bat3hUkmJB4hVh79bf4w_42);	}
	LA34_: ;

#line 85 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(85, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	prepareAdd((&(*res)), 6);appendString((&(*res)), TM__bQ89bat3hUkmJB4hVh79bf4w_44);
#line 86 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(86, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	prepareAdd((&(*res)), 2);appendString((&(*res)), TM__bQ89bat3hUkmJB4hVh79bf4w_45);
#line 89 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(89, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	nimln_(49, "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 89 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(89, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 89 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"

#line 89 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	T36_.len = 0; T36_.p = NIM_NIL;	T36_ = dollar___Ak5SZt3EVWRKrcMjBNQjBA((*x).domain);
#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	nimln_(49, "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");	eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD__7), T36_);
	prepareAdd((&(*res)), colontmpD__7.len + 0);appendString((&(*res)), colontmpD__7);
#line 90 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(90, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	firstElement = NIM_FALSE;
#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(83, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	{
#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		if (!!(firstElement)) goto LA39_;

#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		prepareAdd((&(*res)), 2);appendString((&(*res)), TM__bQ89bat3hUkmJB4hVh79bf4w_46);	}
	LA39_: ;

#line 85 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(85, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	prepareAdd((&(*res)), 8);appendString((&(*res)), TM__bQ89bat3hUkmJB4hVh79bf4w_48);
#line 86 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(86, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	prepareAdd((&(*res)), 2);appendString((&(*res)), TM__bQ89bat3hUkmJB4hVh79bf4w_49);
#line 89 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(89, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	nimln_(49, "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 89 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(89, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 89 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"

#line 89 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	T41_.len = 0; T41_.p = NIM_NIL;	T41_ = dollar___cm8O0zVbDQ8zSf631WHXOw((*x).sockType);
#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	nimln_(49, "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");	eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD__8), T41_);
	prepareAdd((&(*res)), colontmpD__8.len + 0);appendString((&(*res)), colontmpD__8);
#line 90 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(90, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	firstElement = NIM_FALSE;
#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(83, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	{
#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		if (!!(firstElement)) goto LA44_;

#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		prepareAdd((&(*res)), 2);appendString((&(*res)), TM__bQ89bat3hUkmJB4hVh79bf4w_50);	}
	LA44_: ;

#line 85 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(85, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	prepareAdd((&(*res)), 8);appendString((&(*res)), TM__bQ89bat3hUkmJB4hVh79bf4w_52);
#line 86 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(86, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	prepareAdd((&(*res)), 2);appendString((&(*res)), TM__bQ89bat3hUkmJB4hVh79bf4w_53);
#line 89 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(89, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	nimln_(49, "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 89 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(89, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 89 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"

#line 89 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	T46_.len = 0; T46_.p = NIM_NIL;	T46_ = dollar___NC3vOXFMeN9av3LzEF7uXbg((*x).protocol);
#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	nimln_(49, "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");	eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD__9), T46_);
	prepareAdd((&(*res)), colontmpD__9.len + 0);appendString((&(*res)), colontmpD__9);
#line 90 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(90, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	firstElement = NIM_FALSE;
#line 94 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(94, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	nimAddCharV1((&(*res)), 41);	{		LA1_:;	}
	{
#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		nimln_(49, "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__9));

#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__8));

#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__7));

#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__6));

#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__5));

#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__4));

#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__3));

#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__2));

#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();}

#line 109 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringV2, repr__bed2yRJ9cgOSUKAUEFA8J1A)(tyObject_SocketImpl__aIhANOOoETolVz9cccNO9cRQ* x) {	NimStringV2 result;NIM_BOOL* nimErr_;	nimfr_("repr", "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");{nimErr_ = nimErrorFlag();	result.len = 0; result.p = NIM_NIL;
#line 110 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(110, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	{
#line 110 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		if (!(x == 0)) goto LA3_;

#line 110 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"

#line 110 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		result = TM__bQ89bat3hUkmJB4hVh79bf4w_3;		goto BeforeRet_;
	}
	LA3_: ;

#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	nimln_(49, "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	eqsink___aBBXmHFBEivKqERloP6zmA((&result), TM__bQ89bat3hUkmJB4hVh79bf4w_5);

#line 113 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(113, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 113 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	reprObject__rpxzovMTAQ5iPPdHLFpTcQ((&result), (&(*x)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();	return result;}

#line 43 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringV2, repr__tW8HvRRkF7aw2PEMA5Vx9bA)(NimStringV2 x) {	NimStringV2 result;	NimStringV2 T1_;	nimfr_("repr", "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	result.len = 0; result.p = NIM_NIL;
#line 46 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(46, "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 46 "/home/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	T1_.len = 0; T1_.p = NIM_NIL;	T1_ = rawNewString(x.len + 2);appendChar((&T1_), 34);appendString((&T1_), x);appendChar((&T1_), 34);	result = T1_;	popFrame();	return result;}
