/* Generated by Nim Compiler v1.3.5 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct tyObject_TimezonecolonObjectType___F8OvqlxXyGXRSiK9c1fCDVw tyObject_TimezonecolonObjectType___F8OvqlxXyGXRSiK9c1fCDVw;
typedef struct tyObject_ZonedTime__WigfH9apQAxJ69bBPh3wB8RQ tyObject_ZonedTime__WigfH9apQAxJ69bBPh3wB8RQ;
typedef struct tyObject_Time__3y2ZpqsTJLqdZvpC9a0rU2Q tyObject_Time__3y2ZpqsTJLqdZvpC9a0rU2Q;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyTuple__JfHvHzMrhKkWAUvQKe0i1A tyTuple__JfHvHzMrhKkWAUvQKe0i1A;
typedef struct tyObject_Env_timesdotnim___diB2NTuAIWY0FO9c5IUJRGg tyObject_Env_timesdotnim___diB2NTuAIWY0FO9c5IUJRGg;
typedef struct tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw;

/* section: NIM_merge_TYPES */
struct tyObject_Time__3y2ZpqsTJLqdZvpC9a0rU2Q {NI64 seconds;
NI nanosecond;
};
struct tyObject_ZonedTime__WigfH9apQAxJ69bBPh3wB8RQ {tyObject_Time__3y2ZpqsTJLqdZvpC9a0rU2Q time;
NI utcOffset;
NIM_BOOL isDst;
};
typedef struct {
N_NIMCALL_PTR(tyObject_ZonedTime__WigfH9apQAxJ69bBPh3wB8RQ, ClP_0) (tyObject_Time__3y2ZpqsTJLqdZvpC9a0rU2Q x, void* ClE_0);
void* ClE_0;
} tyProc__7xnKxEC24cr3qZyj3gX32w;
struct TGenericSeq {NI len;
NI reserved;
};
struct NimStringDesc {  TGenericSeq Sup;NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_TimezonecolonObjectType___F8OvqlxXyGXRSiK9c1fCDVw {tyProc__7xnKxEC24cr3qZyj3gX32w zonedTimeFromTimeImpl;
tyProc__7xnKxEC24cr3qZyj3gX32w zonedTimeFromAdjTimeImpl;
NimStringDesc* name;
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct tyTuple__JfHvHzMrhKkWAUvQKe0i1A {
void* Field0;
tyObject_Env_timesdotnim___diB2NTuAIWY0FO9c5IUJRGg* Field1;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw {NI64 seconds;
NI nanosecond;
};
typedef NU8 tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ;
typedef NI64 tyArray__pDfjTbtkTNjmi9bTcaNV32Q[8];

/* section: NIM_merge_PROC_HEADERS */
N_LIB_PRIVATE N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef__9a5v4OQPlGqsA25ioN8hFYA)(void* p, NI op);
static N_NIMCALL(void, TM__6NbDwwj5FY059b1gz2AsAZQ_4)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimRegisterThreadLocalMarker)(tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
static N_NIMCALL(void, TM__6NbDwwj5FY059b1gz2AsAZQ_5)(void);
static N_INLINE(NI64, convert__2z1a0DRE31bT73xgVvBfQAtimes)(tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ unitFrom, tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ unitTo, NI64 quantity);
N_LIB_PRIVATE N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NIM_BOOL, nimDivInt64)(NI64 a, NI64 b, NI64* res);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL, nimMulInt64)(NI64 a, NI64 b, NI64* res);
static N_INLINE(NF, toBiggestFloat__hTpm9cXKgh17pxyZUsNnUyQsystem)(NI64 i);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NF, abs__BRaAqinz6OWTHkALb4oj6Qsystem)(NF x);
static N_INLINE(NIM_BOOL, nimAddInt64)(NI64 a, NI64 b, NI64* res);
static N_INLINE(NI, convert__vsrmXCcg8GubJb67VXeq4wtimes)(tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ unitFrom, tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ unitTo, NI quantity);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a, NI b, NI* res);
static N_INLINE(NIM_BOOL, nimSubInt64)(NI64 a, NI64 b, NI64* res);
static N_INLINE(NI, convert__bBJ7N1GpubC85YlnXz3nHgtimes)(tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ unitFrom, tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ unitTo, NI quantity);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw, normalize__JK8O6vJVu4WsESmu0kL4aQ)(NI64 seconds, NI64 nanoseconds);

/* section: NIM_merge_DATA */
N_LIB_PRIVATE TNimType NTI__F8OvqlxXyGXRSiK9c1fCDVw_;
N_LIB_PRIVATE TNimType NTI__7xnKxEC24cr3qZyj3gX32w_;
extern TNimType NTI__vr5DoT1jILTGdRlYv1OYpw_;
extern TNimType NTI__HsJiUUcO9cHBdUCi0HwkSTA_;
extern TNimType NTI__77mFvmsOLKik79ci2hXkHEg_;
N_LIB_PRIVATE TNimType NTI__9a5v4OQPlGqsA25ioN8hFYA_;
N_LIB_PRIVATE NIM_CONST tyArray__pDfjTbtkTNjmi9bTcaNV32Q unitWeights__cpugRVHYEC9bUpLa71eZMsQ = {IL64(1),
IL64(1000),
IL64(1000000),
IL64(1000000000),
IL64(60000000000),
IL64(3600000000000),
IL64(86400000000000),
IL64(604800000000000)}
;

/* section: NIM_merge_VARS */
N_LIB_PRIVATE NIM_THREADVAR tyObject_TimezonecolonObjectType___F8OvqlxXyGXRSiK9c1fCDVw* utcInstance__oeKVHn4dFpBJO35HhEkelw;
N_LIB_PRIVATE NIM_THREADVAR tyObject_TimezonecolonObjectType___F8OvqlxXyGXRSiK9c1fCDVw* localInstance__cLtN9cK9bCe6IPhJ3UFNLNKA;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;

/* section: NIM_merge_PROCS */
static N_NIMCALL(void, Marker_tyRef__9a5v4OQPlGqsA25ioN8hFYA)(void* p, NI op) {
	tyObject_TimezonecolonObjectType___F8OvqlxXyGXRSiK9c1fCDVw* a;
	a = (tyObject_TimezonecolonObjectType___F8OvqlxXyGXRSiK9c1fCDVw*)p;
	nimGCvisit((void*)(*a).zonedTimeFromTimeImpl.ClE_0, op);	nimGCvisit((void*)(*a).zonedTimeFromAdjTimeImpl.ClE_0, op);	nimGCvisit((void*)(*a).name, op);}
static N_NIMCALL(void, TM__6NbDwwj5FY059b1gz2AsAZQ_4)(void) {
	nimGCvisit((void*)utcInstance__oeKVHn4dFpBJO35HhEkelw, 0);}
static N_NIMCALL(void, TM__6NbDwwj5FY059b1gz2AsAZQ_5)(void) {
	nimGCvisit((void*)localInstance__cLtN9cK9bCe6IPhJ3UFNLNKA, 0);}

#line 123 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
static N_INLINE(NIM_BOOL, nimDivInt64)(NI64 a, NI64 b, NI64* res) {	NIM_BOOL result;	result = (NIM_BOOL)0;
#line 117 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
	{		NIM_BOOL T3_;
#line 117 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (NIM_BOOL)0;
#line 117 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (a == (IL64(-9223372036854775807) - IL64(1)));		if (!(T3_)) goto LA4_;

#line 117 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (b == IL64(-1));		LA4_: ;
		if (!T3_) goto LA5_;

#line 118 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		result = NIM_TRUE;	}
	goto LA1_;
	LA5_: ;
	{
#line 120 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 120 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		(*res) = (NI64)(a / b);	}
	LA1_: ;
	return result;}

#line 549 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 550 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 550 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA3_;

#line 551 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 554 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 554 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 556 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 557 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 558 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 558 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 558 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 558 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}

#line 85 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 86 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}

#line 1405 "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim"
static N_INLINE(NF, toBiggestFloat__hTpm9cXKgh17pxyZUsNnUyQsystem)(NI64 i) {	NF result;	nimfr_("toBiggestFloat", "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim");	result = (NF)0;
#line 1406 "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim"
	nimln_(1406, "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim");	result = ((NF) (i));	popFrame();	return result;}

#line 1490 "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim"
static N_INLINE(NF, abs__BRaAqinz6OWTHkALb4oj6Qsystem)(NF x) {	NF result;	result = (NF)0;
#line 1491 "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim"

#line 1491 "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim"
	{
#line 1491 "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim"
		if (!(x < 0.0)) goto LA3_;

#line 1491 "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim"
		result = -(x);	}
	goto LA1_;
	LA3_: ;
	{		result = x;	}
	LA1_: ;
	return result;}

#line 111 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
static N_INLINE(NIM_BOOL, nimMulInt64)(NI64 a, NI64 b, NI64* res) {	NIM_BOOL result;	NI64 r;	NF floatProd;	NF T1_;	NF T2_;	NF resAsFloat;	result = (NIM_BOOL)0;
#line 90 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 90 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
	r = ((NI64) ((NU64)((NU64)(((NU64) (a))) * (NU64)(((NU64) (b))))));
#line 91 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 91 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 91 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 91 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
	T1_ = (NF)0;	T1_ = toBiggestFloat__hTpm9cXKgh17pxyZUsNnUyQsystem(a);
#line 91 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 91 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
	T2_ = (NF)0;	T2_ = toBiggestFloat__hTpm9cXKgh17pxyZUsNnUyQsystem(b);	floatProd = ((NF)(T1_) * (NF)(T2_));
#line 92 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 92 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
	resAsFloat = toBiggestFloat__hTpm9cXKgh17pxyZUsNnUyQsystem(r);
#line 95 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
	{
#line 95 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		if (!(resAsFloat == floatProd)) goto LA5_;

#line 96 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		(*res) = r;	}
	goto LA3_;
	LA5_: ;
	{
#line 105 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		{			NF T10_;			NF T11_;
#line 105 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 105 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 105 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 105 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 105 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
			T10_ = (NF)0;			T10_ = abs__BRaAqinz6OWTHkALb4oj6Qsystem(((NF)(resAsFloat) - (NF)(floatProd)));
#line 105 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 105 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
			T11_ = (NF)0;			T11_ = abs__BRaAqinz6OWTHkALb4oj6Qsystem(floatProd);			if (!(((NF)(3.2000000000000000e+01) * (NF)(T10_)) <= T11_)) goto LA12_;

#line 106 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
			(*res) = r;		}
		goto LA8_;
		LA12_: ;
		{
#line 108 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
			result = NIM_TRUE;		}
		LA8_: ;
	}
	LA3_: ;
	return result;}

#line 399 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
static N_INLINE(NI64, convert__2z1a0DRE31bT73xgVvBfQAtimes)(tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ unitFrom, tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ unitTo, NI64 quantity) {	NI64 result;	nimfr_("convert", "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");	result = (NI64)0;
#line 401 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(401, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 407 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(407, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");	{		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_6;		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_7;
#line 407 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		if (!(unitFrom < unitTo)) goto LA3_;

#line 408 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		nimln_(408, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 408 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		if (unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitFrom)- 0] == 0){ raiseDivByZero(); }		if (nimDivInt64(unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitTo)- 0], unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitFrom)- 0], &TM__6NbDwwj5FY059b1gz2AsAZQ_6)) { raiseOverflow(); };		if ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_6) == 0){ raiseDivByZero(); }		if (nimDivInt64(quantity, (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_6), &TM__6NbDwwj5FY059b1gz2AsAZQ_7)) { raiseOverflow(); };		result = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_7);	}
	goto LA1_;
	LA3_: ;
	{		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_8;		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_9;
#line 410 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		nimln_(410, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 410 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		if (unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitTo)- 0] == 0){ raiseDivByZero(); }		if (nimDivInt64(unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitFrom)- 0], unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitTo)- 0], &TM__6NbDwwj5FY059b1gz2AsAZQ_8)) { raiseOverflow(); };		if (nimMulInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_8), quantity, &TM__6NbDwwj5FY059b1gz2AsAZQ_9)) { raiseOverflow(); };		result = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_9);	}
	LA1_: ;
	popFrame();	return result;}

#line 53 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
static N_INLINE(NIM_BOOL, nimAddInt64)(NI64 a, NI64 b, NI64* res) {	NIM_BOOL result;	NI64 r;	result = (NIM_BOOL)0;
#line 46 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 46 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
	r = ((NI64) ((NU64)((NU64)(((NU64) (a))) + (NU64)(((NU64) (b))))));
#line 47 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
	{		NIM_BOOL T3_;
#line 47 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (NIM_BOOL)0;
#line 47 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 47 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (IL64(0) <= (NI64)(r ^ a));		if (T3_) goto LA4_;

#line 47 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 47 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (IL64(0) <= (NI64)(r ^ b));		LA4_: ;
		if (!T3_) goto LA5_;

#line 48 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		(*res) = r;	}
	goto LA1_;
	LA5_: ;
	{
#line 50 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		result = NIM_TRUE;	}
	LA1_: ;
	return result;}

#line 399 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
static N_INLINE(NI, convert__vsrmXCcg8GubJb67VXeq4wtimes)(tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ unitFrom, tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ unitTo, NI quantity) {	NI result;	nimfr_("convert", "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");	result = (NI)0;
#line 401 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(401, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 407 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(407, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");	{		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_11;		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_12;
#line 407 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		if (!(unitFrom < unitTo)) goto LA3_;

#line 408 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		nimln_(408, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 408 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		if (unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitFrom)- 0] == 0){ raiseDivByZero(); }		if (nimDivInt64(unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitTo)- 0], unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitFrom)- 0], &TM__6NbDwwj5FY059b1gz2AsAZQ_11)) { raiseOverflow(); };		if ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_11) == 0){ raiseDivByZero(); }		if (nimDivInt64(((NI64) (quantity)), (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_11), &TM__6NbDwwj5FY059b1gz2AsAZQ_12)) { raiseOverflow(); };		if (((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_12)) < ((NI) (-2147483647 -1)) || ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_12)) > ((NI) 2147483647)){ raiseRangeErrorI((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_12), ((NI) (-2147483647 -1)), ((NI) 2147483647)); }		result = ((NI) ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_12)));	}
	goto LA1_;
	LA3_: ;
	{		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_13;		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_14;
#line 410 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		nimln_(410, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 410 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		if (unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitTo)- 0] == 0){ raiseDivByZero(); }		if (nimDivInt64(unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitFrom)- 0], unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitTo)- 0], &TM__6NbDwwj5FY059b1gz2AsAZQ_13)) { raiseOverflow(); };		if (nimMulInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_13), ((NI64) (quantity)), &TM__6NbDwwj5FY059b1gz2AsAZQ_14)) { raiseOverflow(); };		if (((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_14)) < ((NI) (-2147483647 -1)) || ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_14)) > ((NI) 2147483647)){ raiseRangeErrorI((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_14), ((NI) (-2147483647 -1)), ((NI) 2147483647)); }		result = ((NI) ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_14)));	}
	LA1_: ;
	popFrame();	return result;}

#line 64 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
static N_INLINE(NIM_BOOL, nimSubInt)(NI a, NI b, NI* res) {	NIM_BOOL result;	NI r;	result = (NIM_BOOL)0;
#line 58 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 58 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
	r = ((NI) ((NU)((NU32)(((NU) (a))) - (NU32)(((NU) (b))))));
#line 59 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
	{		NIM_BOOL T3_;
#line 59 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (NIM_BOOL)0;
#line 59 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 59 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (((NI) 0) <= (NI)(r ^ a));		if (T3_) goto LA4_;

#line 59 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 59 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 59 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (((NI) 0) <= (NI)(r ^ (NI)((NU32) ~(b))));		LA4_: ;
		if (!T3_) goto LA5_;

#line 60 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		(*res) = r;	}
	goto LA1_;
	LA5_: ;
	{
#line 62 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		result = NIM_TRUE;	}
	LA1_: ;
	return result;}

#line 65 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
static N_INLINE(NIM_BOOL, nimSubInt64)(NI64 a, NI64 b, NI64* res) {	NIM_BOOL result;	NI64 r;	result = (NIM_BOOL)0;
#line 58 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 58 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
	r = ((NI64) ((NU64)((NU64)(((NU64) (a))) - (NU64)(((NU64) (b))))));
#line 59 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
	{		NIM_BOOL T3_;
#line 59 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (NIM_BOOL)0;
#line 59 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 59 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (IL64(0) <= (NI64)(r ^ a));		if (T3_) goto LA4_;

#line 59 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 59 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 59 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (IL64(0) <= (NI64)(r ^ (NI64)((NU64) ~(b))));		LA4_: ;
		if (!T3_) goto LA5_;

#line 60 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		(*res) = r;	}
	goto LA1_;
	LA5_: ;
	{
#line 62 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		result = NIM_TRUE;	}
	LA1_: ;
	return result;}

#line 399 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
static N_INLINE(NI, convert__bBJ7N1GpubC85YlnXz3nHgtimes)(tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ unitFrom, tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ unitTo, NI quantity) {	NI result;	nimfr_("convert", "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");	result = (NI)0;
#line 401 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(401, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 407 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(407, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");	{		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_17;		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_18;
#line 407 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		if (!(unitFrom < unitTo)) goto LA3_;

#line 408 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		nimln_(408, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 408 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		if (unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitFrom)- 0] == 0){ raiseDivByZero(); }		if (nimDivInt64(unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitTo)- 0], unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitFrom)- 0], &TM__6NbDwwj5FY059b1gz2AsAZQ_17)) { raiseOverflow(); };		if ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_17) == 0){ raiseDivByZero(); }		if (nimDivInt64(((NI64) (quantity)), (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_17), &TM__6NbDwwj5FY059b1gz2AsAZQ_18)) { raiseOverflow(); };		if (((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_18)) < ((NI) 0) || ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_18)) > ((NI) 999999999)){ raiseRangeErrorI((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_18), ((NI) 0), ((NI) 999999999)); }		result = ((NI) ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_18)));	}
	goto LA1_;
	LA3_: ;
	{		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_19;		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_20;
#line 410 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		nimln_(410, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 410 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		if (unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitTo)- 0] == 0){ raiseDivByZero(); }		if (nimDivInt64(unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitFrom)- 0], unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitTo)- 0], &TM__6NbDwwj5FY059b1gz2AsAZQ_19)) { raiseOverflow(); };		if (nimMulInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_19), ((NI64) (quantity)), &TM__6NbDwwj5FY059b1gz2AsAZQ_20)) { raiseOverflow(); };		if (((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_20)) < ((NI) 0) || ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_20)) > ((NI) 999999999)){ raiseRangeErrorI((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_20), ((NI) 0), ((NI) 999999999)); }		result = ((NI) ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_20)));	}
	LA1_: ;
	popFrame();	return result;}

#line 655 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
N_LIB_PRIVATE N_NIMCALL(NI64, inMilliseconds__df0d89cDnRIju9aB6p1W1qVA)(tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw dur) {	NI64 result;	NIM_BOOL correctionX60gensym24345230_;	NIM_BOOL T1_;	nimfr_("inMilliseconds", "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");	result = (NI64)0;
#line 656 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(656, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 608 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(608, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 608 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	T1_ = (NIM_BOOL)0;
#line 608 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	T1_ = (dur.seconds < IL64(0));	if (!(T1_)) goto LA2_;

#line 608 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	T1_ = (((NI) 0) < ((NI) (dur.nanosecond)));	LA2_: ;
	correctionX60gensym24345230_ = T1_;
#line 612 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(612, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");	{		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_10;		NI64 T7_;		NI T8_;		NI TM__6NbDwwj5FY059b1gz2AsAZQ_15;		NI T9_;		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_16;		if (!correctionX60gensym24345230_) goto LA5_;

#line 613 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		nimln_(613, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 613 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"

#line 613 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		if (nimAddInt64(dur.seconds, IL64(1), &TM__6NbDwwj5FY059b1gz2AsAZQ_10)) { raiseOverflow(); };
#line 613 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		T7_ = (NI64)0;		T7_ = convert__2z1a0DRE31bT73xgVvBfQAtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 3), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 2), (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_10));
#line 614 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		nimln_(614, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 615 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		nimln_(615, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 615 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"

#line 615 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		T8_ = (NI)0;		T8_ = convert__vsrmXCcg8GubJb67VXeq4wtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 3), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 0), ((NI) 1));		if (nimSubInt(T8_, ((NI) (dur.nanosecond)), &TM__6NbDwwj5FY059b1gz2AsAZQ_15)) { raiseOverflow(); };
#line 614 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		nimln_(614, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");		T9_ = (NI)0;		T9_ = convert__vsrmXCcg8GubJb67VXeq4wtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 0), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 2), (NI)(TM__6NbDwwj5FY059b1gz2AsAZQ_15));		if (nimSubInt64(T7_, ((NI64) (T9_)), &TM__6NbDwwj5FY059b1gz2AsAZQ_16)) { raiseOverflow(); };		result = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_16);	}
	goto LA3_;
	LA5_: ;
	{		NI64 T11_;		NI T12_;		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_21;
#line 617 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		nimln_(617, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 617 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"

#line 617 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		T11_ = (NI64)0;		T11_ = convert__2z1a0DRE31bT73xgVvBfQAtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 3), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 2), dur.seconds);
#line 618 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		nimln_(618, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 618 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		T12_ = (NI)0;		T12_ = convert__bBJ7N1GpubC85YlnXz3nHgtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 0), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 2), dur.nanosecond);		if (nimAddInt64(T11_, ((NI64) (T12_)), &TM__6NbDwwj5FY059b1gz2AsAZQ_21)) { raiseOverflow(); };		result = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_21);	}
	LA3_: ;
	popFrame();	return result;}

#line 22 "/home/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size) {	void* T1_;
#line 24 "/home/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"

#line 24 "/home/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memset(a, v, ((size_t) (size)));}

#line 33 "/home/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
#line 34 "/home/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"

#line 34 "/home/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
	nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory(p, ((int) 0), size);
}

#line 412 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw, normalize__JK8O6vJVu4WsESmu0kL4aQ)(NI64 seconds, NI64 nanoseconds) {	tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw result;	NI64 T1_;	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_34;	NI64 nanosecond;	NI T2_;	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_35;	nimfr_("normalize", "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");	nimZeroMem((void*)(&result), sizeof(tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw));
#line 416 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(416, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 416 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"

#line 416 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"

#line 416 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	T1_ = (NI64)0;	T1_ = convert__2z1a0DRE31bT73xgVvBfQAtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 0), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 3), nanoseconds);	if (nimAddInt64(seconds, T1_, &TM__6NbDwwj5FY059b1gz2AsAZQ_34)) { raiseOverflow(); };	result.seconds = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_34);
#line 417 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(417, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 417 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"

#line 417 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"

#line 417 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	T2_ = (NI)0;	T2_ = convert__vsrmXCcg8GubJb67VXeq4wtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 3), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 0), ((NI) 1));	if (((NI64) (T2_)) == 0){ raiseDivByZero(); }	if (nimModInt64(nanoseconds, ((NI64) (T2_)), &TM__6NbDwwj5FY059b1gz2AsAZQ_35)) { raiseOverflow(); };	nanosecond = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_35);
#line 418 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(418, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");	{		NI T7_;		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_36;		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_37;
#line 418 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		if (!(nanosecond < IL64(0))) goto LA5_;

#line 419 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		nimln_(419, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 419 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"

#line 419 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		T7_ = (NI)0;		T7_ = convert__vsrmXCcg8GubJb67VXeq4wtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 3), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 0), ((NI) 1));		if (nimAddInt64(nanosecond, ((NI64) (T7_)), &TM__6NbDwwj5FY059b1gz2AsAZQ_36)) { raiseOverflow(); };		nanosecond = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_36);
#line 420 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		nimln_(420, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");		if (nimSubInt64(result.seconds, ((NI) 1), &TM__6NbDwwj5FY059b1gz2AsAZQ_37)) { raiseOverflow(); };		result.seconds = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_37);	}
	LA5_: ;

#line 421 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(421, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");	if ((nanosecond) < ((NI) (-2147483647 -1)) || (nanosecond) > ((NI) 2147483647)){ raiseRangeErrorI(nanosecond, ((NI) (-2147483647 -1)), ((NI) 2147483647)); }	if ((((NI) (nanosecond))) < ((NI) 0) || (((NI) (nanosecond))) > ((NI) 999999999)){ raiseRangeErrorI(((NI) (nanosecond)), ((NI) 0), ((NI) 999999999)); }	result.nanosecond = ((NI) (((NI) (nanosecond))));	popFrame();	return result;}

#line 579 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw, initDuration__wcR3zetvspAUsyuvWZ07Xg)(NI64 nanoseconds, NI64 microseconds, NI64 milliseconds, NI64 seconds, NI64 minutes, NI64 hours, NI64 days, NI64 weeks) {	tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw result;	NI64 seconds_2;	NI64 T1_;	NI64 T2_;	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_22;	NI64 T3_;	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_23;	NI64 T4_;	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_24;	NI64 T5_;	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_25;	NI64 T6_;	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_26;	NI64 T7_;	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_27;	NI64 T8_;	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_28;	NI nanoseconds_2;	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_29;	NI64 T9_;	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_30;	NI64 T10_;	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_31;	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_32;	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_33;	nimfr_("initDuration", "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");	nimZeroMem((void*)(&result), sizeof(tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw));
#line 587 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(587, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 593 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(593, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 592 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(592, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 591 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(591, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 590 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(590, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 589 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(589, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 588 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(588, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 587 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(587, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 587 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"

#line 587 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	T1_ = (NI64)0;	T1_ = convert__2z1a0DRE31bT73xgVvBfQAtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 7), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 3), weeks);
#line 588 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(588, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 588 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	T2_ = (NI64)0;	T2_ = convert__2z1a0DRE31bT73xgVvBfQAtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 6), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 3), days);	if (nimAddInt64(T1_, T2_, &TM__6NbDwwj5FY059b1gz2AsAZQ_22)) { raiseOverflow(); };
#line 589 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(589, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 589 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	T3_ = (NI64)0;	T3_ = convert__2z1a0DRE31bT73xgVvBfQAtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 4), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 3), minutes);	if (nimAddInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_22), T3_, &TM__6NbDwwj5FY059b1gz2AsAZQ_23)) { raiseOverflow(); };
#line 590 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(590, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 590 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	T4_ = (NI64)0;	T4_ = convert__2z1a0DRE31bT73xgVvBfQAtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 5), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 3), hours);	if (nimAddInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_23), T4_, &TM__6NbDwwj5FY059b1gz2AsAZQ_24)) { raiseOverflow(); };
#line 591 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(591, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 591 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	T5_ = (NI64)0;	T5_ = convert__2z1a0DRE31bT73xgVvBfQAtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 3), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 3), seconds);	if (nimAddInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_24), T5_, &TM__6NbDwwj5FY059b1gz2AsAZQ_25)) { raiseOverflow(); };
#line 592 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(592, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 592 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	T6_ = (NI64)0;	T6_ = convert__2z1a0DRE31bT73xgVvBfQAtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 2), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 3), milliseconds);	if (nimAddInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_25), T6_, &TM__6NbDwwj5FY059b1gz2AsAZQ_26)) { raiseOverflow(); };
#line 593 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(593, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 593 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	T7_ = (NI64)0;	T7_ = convert__2z1a0DRE31bT73xgVvBfQAtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 1), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 3), microseconds);	if (nimAddInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_26), T7_, &TM__6NbDwwj5FY059b1gz2AsAZQ_27)) { raiseOverflow(); };
#line 594 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(594, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 594 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	T8_ = (NI64)0;	T8_ = convert__2z1a0DRE31bT73xgVvBfQAtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 0), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 3), nanoseconds);	if (nimAddInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_27), T8_, &TM__6NbDwwj5FY059b1gz2AsAZQ_28)) { raiseOverflow(); };	seconds_2 = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_28);
#line 595 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(595, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 596 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(596, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 595 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(595, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 595 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"

#line 595 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	if (IL64(1000) == 0){ raiseDivByZero(); }	if (nimModInt64(milliseconds, IL64(1000), &TM__6NbDwwj5FY059b1gz2AsAZQ_29)) { raiseOverflow(); };
#line 595 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	T9_ = (NI64)0;	T9_ = convert__2z1a0DRE31bT73xgVvBfQAtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 2), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 0), (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_29));
#line 596 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(596, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 596 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	if (IL64(1000000) == 0){ raiseDivByZero(); }	if (nimModInt64(microseconds, IL64(1000000), &TM__6NbDwwj5FY059b1gz2AsAZQ_30)) { raiseOverflow(); };
#line 596 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	T10_ = (NI64)0;	T10_ = convert__2z1a0DRE31bT73xgVvBfQAtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 1), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 0), (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_30));	if (nimAddInt64(T9_, T10_, &TM__6NbDwwj5FY059b1gz2AsAZQ_31)) { raiseOverflow(); };
#line 597 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(597, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");	if (IL64(1000000000) == 0){ raiseDivByZero(); }	if (nimModInt64(nanoseconds, IL64(1000000000), &TM__6NbDwwj5FY059b1gz2AsAZQ_32)) { raiseOverflow(); };	if (nimAddInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_31), (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_32), &TM__6NbDwwj5FY059b1gz2AsAZQ_33)) { raiseOverflow(); };	if (((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_33)) < ((NI) (-2147483647 -1)) || ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_33)) > ((NI) 2147483647)){ raiseRangeErrorI((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_33), ((NI) (-2147483647 -1)), ((NI) 2147483647)); }	nanoseconds_2 = ((NI) ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_33)));
#line 599 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(599, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 599 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	result = normalize__JK8O6vJVu4WsESmu0kL4aQ(seconds_2, ((NI64) (nanoseconds_2)));	popFrame();	return result;}
N_LIB_PRIVATE N_NIMCALL(void, stdlib_timesInit000)(void) {

#line 999999 "generated_not_to_break_here"
{
	nimfr_("times", "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");	nimRegisterThreadLocalMarker(TM__6NbDwwj5FY059b1gz2AsAZQ_4);	nimRegisterThreadLocalMarker(TM__6NbDwwj5FY059b1gz2AsAZQ_5);	popFrame();}
}

N_LIB_PRIVATE N_NIMCALL(void, stdlib_timesDatInit000)(void) {

#line 999999 "generated_not_to_break_here"

/* section: NIM_merge_TYPE_INIT1 */
static TNimNode* TM__6NbDwwj5FY059b1gz2AsAZQ_2_3[3];
static TNimNode* TM__6NbDwwj5FY059b1gz2AsAZQ_3_2[2];
static TNimNode TM__6NbDwwj5FY059b1gz2AsAZQ_0[7];
/* section: NIM_merge_TYPE_INIT3 */
NTI__F8OvqlxXyGXRSiK9c1fCDVw_.size = sizeof(tyObject_TimezonecolonObjectType___F8OvqlxXyGXRSiK9c1fCDVw);
NTI__F8OvqlxXyGXRSiK9c1fCDVw_.align = NIM_ALIGNOF(tyObject_TimezonecolonObjectType___F8OvqlxXyGXRSiK9c1fCDVw);
NTI__F8OvqlxXyGXRSiK9c1fCDVw_.kind = 18;
NTI__F8OvqlxXyGXRSiK9c1fCDVw_.base = 0;
TM__6NbDwwj5FY059b1gz2AsAZQ_2_3[0] = &TM__6NbDwwj5FY059b1gz2AsAZQ_0[1];
NTI__7xnKxEC24cr3qZyj3gX32w_.size = sizeof(tyTuple__JfHvHzMrhKkWAUvQKe0i1A);
NTI__7xnKxEC24cr3qZyj3gX32w_.align = NIM_ALIGNOF(tyTuple__JfHvHzMrhKkWAUvQKe0i1A);
NTI__7xnKxEC24cr3qZyj3gX32w_.kind = 18;
NTI__7xnKxEC24cr3qZyj3gX32w_.base = 0;
TM__6NbDwwj5FY059b1gz2AsAZQ_3_2[0] = &TM__6NbDwwj5FY059b1gz2AsAZQ_0[3];
TM__6NbDwwj5FY059b1gz2AsAZQ_0[3].kind = 1;
TM__6NbDwwj5FY059b1gz2AsAZQ_0[3].offset = offsetof(tyTuple__JfHvHzMrhKkWAUvQKe0i1A, Field0);
TM__6NbDwwj5FY059b1gz2AsAZQ_0[3].typ = (&NTI__vr5DoT1jILTGdRlYv1OYpw_);
TM__6NbDwwj5FY059b1gz2AsAZQ_0[3].name = "Field0";
TM__6NbDwwj5FY059b1gz2AsAZQ_3_2[1] = &TM__6NbDwwj5FY059b1gz2AsAZQ_0[4];
TM__6NbDwwj5FY059b1gz2AsAZQ_0[4].kind = 1;
TM__6NbDwwj5FY059b1gz2AsAZQ_0[4].offset = offsetof(tyTuple__JfHvHzMrhKkWAUvQKe0i1A, Field1);
TM__6NbDwwj5FY059b1gz2AsAZQ_0[4].typ = (&NTI__HsJiUUcO9cHBdUCi0HwkSTA_);
TM__6NbDwwj5FY059b1gz2AsAZQ_0[4].name = "Field1";
TM__6NbDwwj5FY059b1gz2AsAZQ_0[2].len = 2; TM__6NbDwwj5FY059b1gz2AsAZQ_0[2].kind = 2; TM__6NbDwwj5FY059b1gz2AsAZQ_0[2].sons = &TM__6NbDwwj5FY059b1gz2AsAZQ_3_2[0];
NTI__7xnKxEC24cr3qZyj3gX32w_.node = &TM__6NbDwwj5FY059b1gz2AsAZQ_0[2];
TM__6NbDwwj5FY059b1gz2AsAZQ_0[1].kind = 1;
TM__6NbDwwj5FY059b1gz2AsAZQ_0[1].offset = offsetof(tyObject_TimezonecolonObjectType___F8OvqlxXyGXRSiK9c1fCDVw, zonedTimeFromTimeImpl);
TM__6NbDwwj5FY059b1gz2AsAZQ_0[1].typ = (&NTI__7xnKxEC24cr3qZyj3gX32w_);
TM__6NbDwwj5FY059b1gz2AsAZQ_0[1].name = "zonedTimeFromTimeImpl";
TM__6NbDwwj5FY059b1gz2AsAZQ_2_3[1] = &TM__6NbDwwj5FY059b1gz2AsAZQ_0[5];
TM__6NbDwwj5FY059b1gz2AsAZQ_0[5].kind = 1;
TM__6NbDwwj5FY059b1gz2AsAZQ_0[5].offset = offsetof(tyObject_TimezonecolonObjectType___F8OvqlxXyGXRSiK9c1fCDVw, zonedTimeFromAdjTimeImpl);
TM__6NbDwwj5FY059b1gz2AsAZQ_0[5].typ = (&NTI__7xnKxEC24cr3qZyj3gX32w_);
TM__6NbDwwj5FY059b1gz2AsAZQ_0[5].name = "zonedTimeFromAdjTimeImpl";
TM__6NbDwwj5FY059b1gz2AsAZQ_2_3[2] = &TM__6NbDwwj5FY059b1gz2AsAZQ_0[6];
TM__6NbDwwj5FY059b1gz2AsAZQ_0[6].kind = 1;
TM__6NbDwwj5FY059b1gz2AsAZQ_0[6].offset = offsetof(tyObject_TimezonecolonObjectType___F8OvqlxXyGXRSiK9c1fCDVw, name);
TM__6NbDwwj5FY059b1gz2AsAZQ_0[6].typ = (&NTI__77mFvmsOLKik79ci2hXkHEg_);
TM__6NbDwwj5FY059b1gz2AsAZQ_0[6].name = "name";
TM__6NbDwwj5FY059b1gz2AsAZQ_0[0].len = 3; TM__6NbDwwj5FY059b1gz2AsAZQ_0[0].kind = 2; TM__6NbDwwj5FY059b1gz2AsAZQ_0[0].sons = &TM__6NbDwwj5FY059b1gz2AsAZQ_2_3[0];
NTI__F8OvqlxXyGXRSiK9c1fCDVw_.node = &TM__6NbDwwj5FY059b1gz2AsAZQ_0[0];
NTI__9a5v4OQPlGqsA25ioN8hFYA_.size = sizeof(tyObject_TimezonecolonObjectType___F8OvqlxXyGXRSiK9c1fCDVw*);
NTI__9a5v4OQPlGqsA25ioN8hFYA_.align = NIM_ALIGNOF(tyObject_TimezonecolonObjectType___F8OvqlxXyGXRSiK9c1fCDVw*);
NTI__9a5v4OQPlGqsA25ioN8hFYA_.kind = 22;
NTI__9a5v4OQPlGqsA25ioN8hFYA_.base = (&NTI__F8OvqlxXyGXRSiK9c1fCDVw_);
NTI__9a5v4OQPlGqsA25ioN8hFYA_.marker = Marker_tyRef__9a5v4OQPlGqsA25ioN8hFYA;
}

